### ISSUE TITLE
Form submission with button component.

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/SQLpage#113]
### Discussed in https://github.com/lovasoa/SQLpage/discussions/112

<div type='discussions-op-text'>

<sup>Originally posted by **Pieter3033** October 24, 2023</sup>
Hi, 

Is it possible to do a form submission with the button component, I know there is already buttons implemented inside of the form but I would like to do a form submission with the fancy new buttons.

Regards</div>

**Comment by lovasoa** [comment]
- The `button` component could add 
     -  a `form` row-level property that takes a form id
     - a `formaction` row-level property to allow multiple buttons to target the same form
 - The form component should add
     - an `id` top-level property

**Comment by Pieter3033** [comment]
Hi, love the idea.

You should have in mind that one button should probably be able to handle multiple form submissions, considering that a form could only have one title.
(As the title is a Top-level parameter [_Please correct me if I'm wrong_])
(The title separates the different inputs for the forms.)

Just spitballing here, but maybe adding a `array of form id's` in the button component, which will allow the button to handle multiple form submissions?

**Comment by Pieter3033** [comment]
I see, I'll have to do some research and get back to this topic.

**Comment by lovasoa** [comment]
Implemented in 8d3c8dcf340770eaa4498ccef6a4b54721a39aac . It will be in the next release :tada:
