### ISSUE TITLE
Align table column right or centre

### ISSUE THREAD

**Issue by lukavia** [lovasoa/SQLpage#115]
I have an application that deals with currency amounts in table. 
It would be nice if I can select certain columns (usually that deals with fractional numbers) to align right instead of left.  
May be something like markdown: 

```sql
SELECT 'table' as component, 'Amount' as right;
```

**Comment by lovasoa** [comment]
I implemented it, it'll be in v0.15

**Comment by lukavia** [comment]
It's perfect! 
Thank you very much!

This is great work. I've been thinking of writing something similar for years, but I just didn't have the time. 
Now that I've found SQLPage It would make things happend. 
Keep up with this great work and I hope I can contribute very soon.
Cheers
