### ISSUE TITLE
user login and session

### ISSUE THREAD

**Issue by dawsongzhao0523** [lovasoa/SQLpage#12]
we think it is time to add security framework that performs authentication, authorization, cryptography, and session management for sqlpage after building a demo for teammate.

**Comment by lovasoa** [comment]
That is in my plans for the future of SQLite. At the moment, you have to handle this the traditional way, creating an user table, using the `form` component to ask for username and password, and using something like [pgcrypto](https://www.postgresql.org/docs/current/pgcrypto.html) to hash passwords.

**Comment by lovasoa** [comment]
One thing that I would like to add first is support for cookies. Then, it will be support for oidc with a syntax that will look something like

```sql
SELECT 
   'login' AS 'component',
   'http://example.com/auth/realms/demo/.well-known/openid-configuration' AS openid_configuration,
   'xxx' as client_secret;

SELECT
    'text' AS component,
    'Welcome, ' || json_extract(sqlpage_cookie('jwt'), '$.name') AS contents;
```

**Comment by lovasoa** [comment]
SQLPage v0.7.0 was just released with a cool new feature : it supports cookies.


```sql
-- Sets the username cookie to the value of the username parameter
SELECT 'cookie' as component,
    'username' as name,
    $username as value
WHERE $username IS NOT NULL;

SELECT 'form' as component;
SELECT 'username' as name,
    'User Name' as label,
    COALESCE($username, sqlpage.cookie('username')) as value,
    'try leaving this page and coming back, the value should be saved in a cookie' as description;

select 'text' as component;
select 'log out' as contents, 'logout.sql' as link;
```

logout.sql:

```sql
-- Remove the username cookie
SELECT 'cookie' as component,
    'username' as name,
    TRUE as remove;

SELECT 'http_header' as component, 'index.sql' as Location;
```

**Comment by pinaraf** [comment]
> That is in my plans for the future of SQLite. At the moment, you have to handle this the traditional way, creating an user table, using the `form` component to ask for username and password, and using something like [pgcrypto](https://www.postgresql.org/docs/current/pgcrypto.html) to hash passwords.

Note: this is not a recommended way of doing it since it means sending your clear-text password to the database, thus through any layer in-between. It is always preferred to send hashes instead.

**Comment by lovasoa** [comment]
> this is not a recommended way of doing it since it means sending your clear-text password to the database, thus through any layer in-between. It is always preferred to send hashes instead.

@pinaraf : This used to be true a few years ago, but encrypted database connections have been supported for a long time now, and are now the default for most db providers. SQLPage will use a TLS encrypted connection by default if it's supported by the server. If your threat model includes attackers having access to clear-text communication between your application and the database, you probably have a serious problem in your architecture anyway.

**Comment by pinaraf** [comment]
> > this is not a recommended way of doing it since it means sending your clear-text password to the database, thus through any layer in-between. It is always preferred to send hashes instead.
> 
> @pinaraf : This used to be true a few years ago, but encrypted database connections have been supported for a long time now, and are now the default for most db providers. SQLPage will use a TLS encrypted connection by default if it's supported by the server. If your threat model includes attackers having access to clear-text communication between your application and the database, you probably have a serious problem in your architecture anyway.

Your threat model may imply not sending clear text passwords to DBAs, or to the DB logs if the query ends up being slow for any reason... Also, there are tools that are hopelessly using clear-text sessions (looking at you pgbouncer) that you may encounter in real world.

**Comment by pinaraf** [comment]
BTW, even in PostgreSQL 15, pgcrypto does not include any modern recommended password hashing algorithm. The best it has to offer lags behind the GPU-era, and it would not be before PG17 that anything better could be available (if someone submits such a patch obviously)

**Comment by lovasoa** [comment]
I added a full user authentication demo to this repo: https://github.com/lovasoa/SQLpage/tree/main/examples/user-authentication

I'd love to get feedback from you.

Authentication is the main thing I want to work on for the next version, in order to make it easier, more secure, and to offer multiple authentication options.

**Comment by lovasoa** [comment]
Hello all ! 

I'd like to publish SQLPage v0.7.2 today, with many new features, including a new [authentication](https://sql.ophir.dev/documentation.sql?component=authentication#component) component. 

I'd love it if you could read the documentation and maybe even test the new version on docker ([lovasoa/sqlpage:main](https://hub.docker.com/repository/docker/lovasoa/sqlpage/tags?page=1&ordering=last_updated)) and give feedback before I release it !

**Comment by lovasoa** [comment]
I just released v0.7.2 with all the new features, and updated the authentication example 💫

https://github.com/lovasoa/SQLpage/tree/main/examples/user-authentication

**Comment by fire** [comment]
Is this completed?

**Comment by lovasoa** [comment]
@fire : yes, authentication is fully supported, both using *HTTP Basic Auth* and custom user records and password hashes stored in the database. Check out: 
 - [The documentation for the `authentication` component](https://sql.ophir.dev/documentation.sql?component=authentication#component)
 - [The password hashing documentation](https://sql.ophir.dev/functions.sql?function=hash_password#function)
 - [The `cookie` component that allows you to easily store session cookies](https://sql.ophir.dev/documentation.sql?component=cookie#component)
 - most importantly, the [full authentication web app example source](https://github.com/lovasoa/SQLpage/tree/main/examples/user-authentication)

In addition to these two authentication mechanisms, Single-Sign-On using OIDC is on the roadmap and will be implemented in a future version.

**Comment by lovasoa** [comment]
I made a demo of single-sign-on to a central authentication service using OAuth and OIDC entirely in SQLPage here: https://github.com/lovasoa/SQLpage/tree/main/examples/single%20sign%20on%20with%20openid%20connect
