### ISSUE TITLE
parse error in `FOR JSON PATH`

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/SQLpage#127]
### Discussed in https://github.com/lovasoa/SQLpage/discussions/126

<div type='discussions-op-text'>

<sup>Originally posted by **Pieter3033** November  8, 2023</sup>
Hi,

The newest form component is really cool 🔥.

I am currently struggling to populate the `options `of a `select type` in the `form` component.
I am using MSSQL.

I have attempted the following: 
`(SELECT Column1 AS label, Column2 AS value FROM MyTable FOR JSON PATH) AS options`

Error:
![image](https://github.com/lovasoa/SQLpage/assets/141907966/ef20a898-cc6e-4b81-8597-2035032b9076)

Note, I have tested this SQL statement inside of MSSQL and the output is as expected.
Maybe I am struggling with the syntax?

Regards</div>

**Comment by lovasoa** [comment]
I reported the issue upstream to the sql parser library. 

In the meantime, you have two options:
 - [format the json string manually using string manipulation functions](http://sqlfiddle.com/#!18/58a4b/3)
 - define a [custom function](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-ver16) that returns your json string, and just call that function from your SQL page (`SELECT create_options_json() AS options`)

**Comment by lovasoa** [comment]
I wrote a fix for the parser, waiting for it to get merged: https://github.com/sqlparser-rs/sqlparser-rs/pull/1043

**Comment by Pieter3033** [comment]
Hi @lovasoa, hope you are well.

Love the new update 🔥

I see that the sqlparser has been merged, has it been pushed in SQLPage 0.16.0 ?

**Comment by lovasoa** [comment]
Hi ! I'm fine, thank you :)

My pull request has been merged, but the [new sqlparser still hasn't been released](https://github.com/sqlparser-rs/sqlparser-rs/issues/1030). I'll publish a SQLPage release after the sqlparser releaser, which @alamb should do beginning of next week.

**Comment by Pieter3033** [comment]
Perfect.

Thank you for the feedback.

**Comment by lovasoa** [comment]
Good news for you ! 
Just merged the upstream change, we have `FOR JSON` in the latest development version of SQLPage. 

You can try it now on docker with `lovasoa/sqlpage:main`, or wait for the big release which is coming in the next few days.

**Comment by Pieter3033** [comment]
Perfect thank you for the update, looking forward to the next SQLPage update.

**Comment by lovasoa** [comment]
It's going to be a big one, with some long awaited features :)
