### ISSUE TITLE
Invalid GeoJSON object

### ISSUE THREAD

**Issue by cornerot** [lovasoa/SQLpage#129]
Hi!

I get "Invalid GeoJSON object" error when running the map example from the tutorial:
![2023-11-10T18:29:08,833894328+03:00](https://github.com/lovasoa/SQLpage/assets/2393801/76a12779-a47d-4515-97e9-2e85504ba883)

cat map.sql
```sql
select
    'map'   as component,
    'Paris' as title,
    11      as zoom,
    48.85   as latitude,
    2.34    as longitude,
    400     as height;
select
    'Notre Dame'             as title,
    'building-castle'        as icon,
    'indigo'                 as color,
    48.853                   as latitude,
    2.3498                   as longitude,
    'A beautiful cathedral.' as description_md,
    'https://en.wikipedia.org/wiki/Notre-Dame_de_Paris' as link;
select
    'Eiffel Tower' as title,
    'tower'        as icon,
    'yellow'       as color,
    48.8584        as latitude,
    2.2945         as longitude,
    'A tall tower. [Wikipedia](https://en.wikipedia.org/wiki/Eiffel_Tower)' as description_md;
select
    'Tower to Cathedral'      as title,
    JSON('{"type":"LineString","coordinates":[[2.2945,48.8584],[2.3498,48.8530]]}') as geojson,
    'teal'                    as color,
    'A nice 45 minutes walk.' as description;
```

**Comment by lovasoa** [comment]
Hi ! Which database are you using ? Does it work when passing the json object as a string (`'{"type":"LineString","coordinates":[[2.2945,48.8584],[2.3498,48.8530]]} as geojson`) ?

**Comment by cornerot** [comment]
I don't use a database. Just created the sql file from the tutorial.
The error is the same as with
```sql
JSON('{"type":"LineString","coordinates":[[2.2945,48.8584],[2.3498,48.8530]]}') as geojson
```
or

```sql
'{"type":"LineString","coordinates":[[2.2945,48.8584],[2.3498,48.8530]]}' as geojson
```

**Comment by lovasoa** [comment]
Thank you for the precision. SQLPage is always connected to a database, but if you haven't explicitly configured any database connection, then you are using the default embedded [SQLite](https://en.wikipedia.org/wiki/SQLite) database.

The bug only happens with databases that do not have native json objects. I can reproduce it locally; I'll fix it and release a new version shortly. Thanks for the report !

**Comment by lovasoa** [comment]
v0.15.2 was just released with the fix : https://github.com/lovasoa/SQLpage/releases/tag/v0.15.2
