### ISSUE TITLE
Add unicode support in the built-in SQLite database

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/SQLpage#155]
SQLPage includes a statically linked version of SQLite. 
SQLite by default does not support unicode (for case-insensitive matching, the UPPER and LOWER functions, ...).

To avoid binary bloat, SQLite recommends that applications overload SQLite functions with unicode-aware versions using the unicode libraries the software already uses: https://www.sqlite.org/faq.html#q18

SQLPage could overload unicode functions using rust's standard library unicode-aware functions.

**Comment by lovasoa** [comment]
In the meantime, one can use [Combining Diacritical Marks](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks) instead of accentuated characters: 

```sql
update my_table set my_text_field=
replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(
my_text_field,
'Û','Û'),'Ü','Ü'),'Ý','Ý'),'à','à'),'á','á'),'â','â'),'ã','ã'),'ä','ä'),'ç','ç'),'è','è'),'é','é'),'ê','ê'),'ë','ë'),'ì','ì'),'í','í'),'î','î'),'ï','ï'),'ñ','ñ'),'ò','ò'),'ó','ó'),'ô','ô'),'õ','õ'),'ö','ö'),'ù','ù'),'ú','ú'),'û','û'),'ü','ü'),'ý','ý');
```

[example](https://www.db-fiddle.com/f/7cjQaKKMc6Koh4W1fwFK9f/0)

**Comment by DSMejantel** [comment]
Good idea for "é" with the upper function.
But in french language, we need the same thing for É.
And Émile is after Henri in my list !
