### ISSUE TITLE
Eror in online examples for tracking component

### ISSUE THREAD

**Issue by lorefnon** [lovasoa/SQLpage#167]
Hello, thanks for creating and open sourcing SQLPage. It looks like a great solution for SQL driven reports/dashboards. 

### Introduction

The examples for the tracking component in the site show an error

### To Reproduce

Visit the tracking component docs https://sql.ophir.dev/documentation.sql?component=tracking#component
and scroll down to the examples

### Actual behavior

An error like this can be seen for each example 

![image](https://github.com/lovasoa/SQLpage/assets/1449492/7ff14c66-686b-4aa0-b089-4f25025021eb)

### Expected behavior

Examples should work as expected

**Comment by lovasoa** [comment]
Hello !
  We currently have only one version of the documentation, and it always shows all the bleeding edge features.

  The `tracking` component was [just three days ago](https://github.com/lovasoa/SQLpage/pull/162) and will be part of SQLPage v0.18, which still has not been released. 
  I'll hopefully release it this week, provided I find the time to finish my work on #163 .

 In the meantime, you can always try the latest unreleased features by using [`lovasoa/sqlpage:latest` on docker](https://hub.docker.com/r/lovasoa/sqlpage).

**Comment by lorefnon** [comment]
Oh I see. I'll close this issue in that case. 

I opened this issue just to bring it to notice in case there was some misconfiguration or bug in the examples.

Thanks for your work on SQLPage.

**Comment by lovasoa** [comment]
Oh, I see, you were talking about the website itself, not being unable to use the component for yourself locally. Sorry, I read your issue too fast.

There was indeed a problem with the deployment, it's fixed, thanks for bringing it to my attention.
