### ISSUE TITLE
Server stalls indefinitely

### ISSUE THREAD

**Issue by lorefnon** [lovasoa/SQLpage#189]
### Introduction

I have unfortunately not been able to arrive at a clear minimal reproducer (and will try more over next couple of days) but I frequently encounter a scenario where the server stops responding and all requests gets stuck in pending state. SQLPage becomes completely unusable for all pages/users until the server is restarted. 

I do not see any error in the logs and the Memory/CPU usage stays low (~9.5 MB, ~0) and constant when/after this happens.

Some of our queries are expensive and we don't mind these pages taking long while we are iterating on the final outcome (I am able to run them from psql) but it would be ideal if this didn't impact the availability of the server as whole.  

### Screenshots
![image](https://github.com/lovasoa/SQLpage/assets/1449492/b267d505-7696-4f57-8a78-1e74929f17e7)

### Expected behavior
Server should stay functional.

### Version information

 - OS: Ubuntu
 - Database Postgres (RDS)
 - SQLPage Version main

**Comment by lovasoa** [comment]
This is concerning! Did you try to run SQLPage in debug mode (RUST_LOG=debug) to see where exactly it it stalls?

You can control logging with RUST_LOG=sqlpage=trace to get even more logging, but only from sqlpage, not dependencies.

**Comment by lorefnon** [comment]
I had tried debug before but that was not informative. After enabling trace I could see a message about pg pool getting exhausted

```
[2024-01-15T11:32:47.926Z TRACE sqlpage::webserver::http] Received item from database: Error(Unable to acquire a database connection to execute the SQL file. All of the 6 Postgres connections are busy.

    Caused by:
        pool timed out while waiting for an open connection)
[2024-01-15T11:32:47.927Z ERROR sqlpage::render] SQL error: Unable to acquire a database connection to execute the SQL file. All of the 6 Postgres connections are busy.

    Caused by:
        pool timed out while waiting for an open connection
```

This was strange because: 
- I had no idea where the 6 limit was coming from. The default pool size should be 50. 
- It never recovered from this, irrespective of connection timeout duration.

So I increased the pool size to 100 in sqlpage.json and this message disappeared. 
However the problem remains. After a few dozen or so refreshes my server hangs - I can reproduce this locally too with a locally running postgres so likely not related to RDS or my front proxy config.

**Comment by lovasoa** [comment]
Where exactly does it stall ? You don't even see the initial log about the incoming http connection ?

What do you see on the database side ? How many connections do you see opened and are they busy ?

**Comment by lorefnon** [comment]
If I comment out the `cache.insert(..)` [here](https://github.com/lovasoa/SQLpage/blob/main/src/file_cache.rs#L151) this no longer happens.

**Comment by lovasoa** [comment]
Can you try to make a small docker composer reproduction, or add more trace logging to understand where it stalls ? It would be strange for the hashmap insertion to be what hangs.

**Comment by lorefnon** [comment]
Potentially relevant: https://github.com/xacrimon/dashmap/issues/233

**Comment by lovasoa** [comment]
Interesting ! Can you try replacing the dashmap with a simple RwLock<HashMap<...>> and report if this fixes the issue ? If so, can you make it a pr ?

**Comment by lorefnon** [comment]
`std::sync::RwLock` based impl was getting stuck too. But using `tokio::sync::RwLock` seems to resolve the problem. 

PR: https://github.com/lovasoa/SQLpage/pull/193

**Comment by lovasoa** [comment]
Great that the issue is fixed. However, looking at the code, it seems that we don't really need to hold the lock across an async boundary, do we ?

It happens because of the `if let`, but we could cheaply clone the `Cached` object and immediately release the lock, couldn't we ?

I'm a bit hesitant to change the code again if I cannot reproduce the original issue locally. Do you think you could add a test in https://github.com/lovasoa/SQLpage/tree/main/tests that breaks with the old implementation and passes with the new one ?

**Comment by lorefnon** [comment]
> Do you think you could add a test in https://github.com/lovasoa/SQLpage/tree/main/tests that breaks with the old implementation and passes with the new one ?

I am not too sure about me able to do this, but I'll try over the next week. My familiar with both rust and concurrent systems is quite nascent.  

> looking at the code, it seems that we don't really need to hold the lock across an async boundary...

We kind of do, because we update the access time in cache after verifying that the file has not been modified on disk (and this check is async).

To validate this though, I attempted [a workaround](https://github.com/lovasoa/SQLpage/commit/6f6670747f445f0c84301da990451296eb8dbc54) which retains dashmap but drops the ref obtained from cache before the async call and reloads it from cache after it. This too seems to solve the problem. 

Maybe its just that I am not used to low level programming, but this kind of limitation in a library appears to be a footgun in async heavy code. 

Nevertheless, if you prefer to retain dashmap, here is [an updated PR](https://github.com/lovasoa/SQLpage/pull/195) that retains dashmap and appears to work fine without stalling.
