### ISSUE TITLE
Tutorial invalid syntax

### ISSUE THREAD

**Issue by deliciouslytyped** [lovasoa/SQLpage#192]
Whats the deal with examples on the tutorial page using double single quotes for quoting?
https://sql.ophir.dev/documentation.sql

For example:
```
SELECT ''list'' AS component, ''Popular websites'' AS title;
```

This seems broken and wrong

**Comment by lovasoa** [comment]
Where do you see it rendered like that? Can you provide a screenshot?

https://sql.ophir.dev/documentation.sql?component=list#component

**Comment by lovasoa** [comment]
![Screenshot_20240119-094630_Firefox Beta.png](https://github.com/lovasoa/SQLpage/assets/552629/030702db-b6e1-4725-8579-6848ca181146)

**Comment by lovasoa** [comment]
Oh, I see ! You are referring to https://sql.ophir.dev/your-first-sql-website/ ! 

Let's fix that !
