### ISSUE TITLE
Chart titles gone missing in v0.18.1

### ISSUE THREAD

**Issue by accforgithubtest** [lovasoa/SQLpage#208]
I just updated to the latest version and the chart titles that used to display the title properly before, are all missing the titles now. Seems to be impacting all chart types (line, bar, etc).

(The performance of the pages that used to have multiple bar charts seems to have improved massively - that is superb !! And I am looking forward to trying out the multi column layouts using the updated cards component)

Cheers

**Comment by lovasoa** [comment]
@lorefnon , I think this is caused by my fix of https://github.com/lovasoa/SQLpage/pull/175 :/

**Comment by lorefnon** [comment]
The change in #175 caused both. The fix was just not complete.

**Comment by lovasoa** [comment]
Thanks for the fix, @lorefnon ! I'll try to release v0.18.2 later today.

**Comment by lovasoa** [comment]
v0.18.2 is being built

**Comment by accforgithubtest** [comment]
Confirmed that this is working again in v0.18.2. Thanks !
