### ISSUE TITLE
Regression with 'add an null value as an option in a select '

### ISSUE THREAD

**Issue by DSMejantel** [lovasoa/SQLpage#213]
### Introduction

The question was solved first in discussion #95 
All was fine with SQLpage 0.17.1 but with 0.18.2 we can't see the label for the Null Value in the select list anymore.

### Expected behavior
With 0.17.1
![Capture_0 17 1](https://github.com/lovasoa/SQLpage/assets/149260856/c3d6bc44-83cc-4d6a-aef5-76dc914f0beb)

### Actual behavior
with 0.18.2
![Capture_0 18 2](https://github.com/lovasoa/SQLpage/assets/149260856/db7b9cd1-3cf8-4ea9-a52d-061d256cdaaa)

```sql
    SELECT 'souche' AS name, 'select' as type, 4 as width,
    json_group_array(json_object("label" , numero, "value", numero )) as options FROM (
  SELECT numero, numero FROM colonie
  UNION ALL
  SELECT NULL, 'Inconnue' );
```

### Version information

 - OS: Ubuntu
 - Database Sqlite
 - SQLPage Version : 0.18.2

**Comment by lovasoa** [comment]
How could it know which "numero" is the label and which is the value? You need a different name for the label and the value. 

```
SELECT 'souche' AS name, 'select' as type, 4 as width,
    json_group_array(
        json_object("label" , label, "value", numero )
    ) as options
FROM (
  SELECT numero, numero as label FROM colonie
  UNION ALL
  SELECT NULL, 'Inconnue'
);
```

**Comment by DSMejantel** [comment]
Ohh I understand.
Another argument to keep a separate id and number for the  beehive, maybe ?

**Comment by lovasoa** [comment]
If the "Numero" is unique, then it's ok to use it as id.

**Comment by DSMejantel** [comment]
Yes with Numero and a 'Unique' contrainst, the list select is OK.
I find this soluce to have a good display and manage more information with another table : 
`    SELECT 'souche' AS name, 'select' as type, 4 as width,
    json_group_array(json_object("label" , numero, "value", numero )) as options FROM (
  SELECT numero, numero FROM colonie
  UNION ALL
  SELECT origine, NULL FROM provenance ORDER BY origine asc
)`

**Comment by lovasoa** [comment]
You still have the problematic `json_object("label" , numero, "value", numero`
You cannot give two different columns the same name and then distinguish between them.

**Comment by DSMejantel** [comment]
But I think it's working. Am I wrong ?
![Capture_table](https://github.com/lovasoa/SQLpage/assets/149260856/2c9c7559-ab52-4dd1-aad3-a15002732d12)

**Comment by lovasoa** [comment]
The thing is 

```sql
select json_group_array(json_object("label" , numero, "value", numero )) as options
from anything
```

Cannot produce a json array containing something like `{"label": "inconnue", "value": null }` which is probably what you wanted.
As suggested above, you need something like

```sql
SELECT json_group_array(json_object("label" , label, "value", value)) as options
FROM something
```

where *something* has a `label` and a `value` column. For instance:

```sql
 SELECT json_group_array(json_object("label" , label, "value", value)) as options
FROM (
   select my_id as label, my_id as value from my_table
   union all
   select 'Other' as label, NULL as value
)
```

**Comment by DSMejantel** [comment]
I tried
```
`json_group_array(json_object("label" , label, "value", value)) as options
FROM (
   select numero as label, numero as value from colonie
   union all
   select 'Other' as label, NULL as value
)
```
and
```

json_group_array(json_object("label" , label, "value", value )) as options FROM (
  SELECT numero as label, numero as value FROM colonie
  UNION ALL
  SELECT origine as label, NULL as value FROM provenance ORDER BY origine asc
)
```
But i receive this error : 
```
error returned from database: (code: 1) json_object() labels must be TEXT
(code: 1) json_object() labels must be TEXT
```

**Comment by lovasoa** [comment]
Oh sorry, I messed up the quotes above. It's `json_object('label', label, 'value', value)` not `json_object("label", label, "value", value)`

Single quotes are for Strings Literals,
Double quotes are for Database Identifiers.

**Comment by DSMejantel** [comment]
Thanks. All is now ok and work properly.
```
    SELECT 'souche' AS name, 'select' as type, 4 as width,
    json_group_array(json_object('label' , label, 'value', value )) as options FROM (
  SELECT 'colonie n°'||numero as label, numero as value FROM colonie
  UNION ALL
  SELECT origine as label, NULL as value FROM provenance ORDER BY origine asc
)
```
![Capture_select](https://github.com/lovasoa/SQLpage/assets/149260856/dd08cb79-c0d9-4bce-b36a-ea29ba568335)
