### ISSUE TITLE
file uploads

### ISSUE THREAD

**Issue by gwado** [lovasoa/SQLpage#24]
Hello, 
Is it possible to integrate a "files" or "uploads" component that would make it possible to upload a file via the form?
Each file could be stored in a "uploads" folder (by default) and metadata in a table named "uploads" (by default) with the following fields (e.g.) : id, uuid-name, date-created.

**Comment by lovasoa** [comment]
Hi ! 
  Yes, handling uploads is on the roadmap. But I'm not a huge fan of the `uploads` folder and the `uploads` table.

  SQLPage is completely agnostic to your database or folder structure so far, and I'd like it to stay this way. You can use sqlpage with a read-only database, you can use it with a database on which you don't have the permission to create new tables, you can use it on a read-only filesystem, and that's something I'd like to keep.

  The way I was thinking about this feature was adding [sqlpage pseudo-functions](https://sql.ophir.dev/functions.sql) :
  - `sqlpage.uploaded_file('name')`
  - `sqlpage.base64()` to be used with standard `INSERT` statements to make it easy to save files directly in the database and reuse them
  - and maybe a component to save data to disk (`SELECT 'save_file' AS component, 'xxx' AS filename, sqlpage.uploaded_file('name') AS contents`)

**Comment by gwado** [comment]
Why not use sqlpage/sqlpage.json to allow certain parameters, such as the upload folder, to be modified?
If I'm not mistaken: we can integrate a js script into a template to, for example, resize an image before uploading it. Yes ?

It's true that these reflections are very touchy, because the basic idea of simplicity is excellent, and every addition shouldn't call it into question with the risk of creating a bag of knots.

**Comment by lovasoa** [comment]
Here is what I think needs to be done:

 - Add `enctype=multipart/form-data` to forms in the form component 
 - Add a dependency to [actix-multipart](https://docs.rs/actix-multipart/0.6.0), with the tempfile optional dependency
- Parse request bodies as multipart in `extract_request_info` in http.rs. Save files as tempfiles. 
- Add two new functions  
  - `sqlpage.uploaded_file_dataurl('name')` which returns an uploaded file as a data url
   - `sqlpage.uploaded_file_path('name', 'folder')` which copies the file to the given folder with a secure random name and returns the path

Let me know what you think. If you are interested in implementing it yourself, let me know and I'll guide you through the code and review your pr. If you need that done by me, contact me on [contact at ophir dot dev] and we'll agree on a small dev contract.

**Comment by lovasoa** [comment]
Hey ! It took a long time, but I just merged [the big files update](https://github.com/lovasoa/SQLpage/pull/139). It will be in the next version unless someone finds a big issue with it before the release. The easiest way to test it for now is by using the `lovasoa/sqlpage:main` image on docker.

I think the final result is both easy enough to use and flexible. Have look at the release notes !

**Comment by gwado** [comment]
Excellent news, great work!

I see that there's also a function for reading files (those that are
uploaded). I'll take the time to test uploading and displaying geojson
files.

It's not easy for me to participate in the project. The implementation
is simple, that's the goal and it's successful, but the project itself
remains a black box for me.

Congratulations again!

**Comment by lovasoa** [comment]
If you want to contribute to the project, but don't know rust, a useful thing to do would be contributing to the [examples](https://github.com/lovasoa/SQLpage/tree/main/examples) and to the [official site](https://github.com/lovasoa/SQLpage/tree/main/examples/official-site). Both get a continuous flow of visits, and I think there is still a lot of room for improvement to make them clearer and more pedagogical. A lot of formulations still use technical jargon without defining it.
