### ISSUE TITLE
Add css_class support on table items

### ISSUE THREAD

**Issue by nanawel** [lovasoa/SQLpage#25]
When using the [table component](https://sql.ophir.dev/documentation.sql?component=table#component), it would really be handy to be able to add a CSS class to a row, and even to each column.

For the row, I guess this should not be too hard. I'm not sure about the column though.

This way it could be easy to add background color, special font, etc. depending on data retrieved for each row.

**Comment by lovasoa** [comment]
What exactly are you trying to achieve with that CSS ? Maybe we could add handling for background colors directly in the component ? That seems like a useful thing to be able to do, even without knowing CSS.

We could add a special handling for columns with a name starting with "sqlpage_", So that you can do something like

```sql
SELECT 
    'table' as component;
SELECT 
    1 as "My Fun Column",
    2 as "My Other column";
   'red' as sqlpage_color,
   'hello' as sqlpage_css_class;
```

What d you think ?

**Comment by nanawel** [comment]
> What exactly are you trying to achieve with that CSS?

Be able to colorize each row depending on a calculated field (category, status, etc.).


> ```sql
> SELECT 
>    1 as "My Fun Column",
>    2 as "My Other column";
>   'red' as sqlpage_color,
>   'hello' as sqlpage_css_class;
> ```

Your `sqlpage_css_class` is exactly what I had in mind for the "row" styling part. I'm not sure about the `sqlpage_color`, but I guess it could be something similar to the `color` field on the `list` component.

**Comment by nanawel** [comment]
Btw, I think the same option could be available on the `text` component: an optional CSS class that would be applied to a  `<div>` surrounding all of the `<p>` in order to apply to the the block a special look & feel.

**Comment by nanawel** [comment]
Thanks! :tada:
