### ISSUE TITLE
No error message is displayed when the dynamic component is called with invalid json

### ISSUE THREAD

**Issue by guspower** [lovasoa/SQLpage#314]
### Introduction

I have been successfully setting the shell title from a json file as per the docs. As of the latest release (v0.20.5) neither the custom title or footer are being displayed.

### To Reproduce

Follow a pattern similar to the docs:

index.sql
```sql
SELECT 'dynamic' AS component, sqlpage.read_file_as_text('shell.json') AS properties;
```

shell.json
```json
{
  "component": "shell",
  "title": "Custom Title",
  "link": "/",
  "language": "en-GB",
  "description": "Custom description",
  "font": "Poppins",
  "icon": "book",
  "footer": "Custom Footer 2024"
}
```

### Actual behavior
Instead `SQLPage` renders the default title and footer.

### Expected behavior
The custom shell should be output into the browser.

### Version information

 - OS: `6.6.13-gentoo`
 - Database: `PostgreSQL 16.2 on x86_64-pc-linux-gnu`
 - SQLPage Version: `v0.20.5`

**Comment by lovasoa** [comment]
Hi @guspower ! Can you please provide reproduction steps ? Everything seems to work fine for me.

Here is a replit with the exact shell you are mentioning, which works: https://replit.com/@pimaj62145/SQLPage-dynamic-shell-exemple#index.sql

**Comment by guspower** [comment]
Apologies for raising a bug on Monday morning, I should've figured it was _user error_. Sigh.

It turns out there was a trailing comma in the `shell.json`, e.g. if you have something like:
```
{
  "component": "shell",
  "title": "Custom Title",
  "link": "/",
  "language": "en-GB",
  "description": "Custom description",
  "font": "Poppins",
  "icon": "book",
  "footer": "Custom Footer 2024", <- BOOM
}
```
it doesn't render any error message, it just ignores it.

Sorry for the noise, situation normal.

**Comment by lovasoa** [comment]
I guess not seeing an error message is a problem in itself. Wasn't there anything in the logs either ?

**Comment by guspower** [comment]
Excellent, great outcome @lovasoa !
