### ISSUE TITLE
0.8.0 release build failed

### ISSUE THREAD

**Issue by chenrui333** [lovasoa/SQLpage#32]
👋 it looks like the [0.8.0 release build failed](https://github.com/lovasoa/SQLpage/actions/runs/5569953772/jobs/10173666747).

relates to https://github.com/Homebrew/homebrew-core/pull/136766

**Comment by lovasoa** [comment]
looks like a github runner issue https://github.com/Homebrew/homebrew-core/pull/136766#issuecomment-1637237052

**Comment by lovasoa** [comment]
I reran the action, everything seems to be ok.

https://github.com/lovasoa/SQLpage/releases/tag/v0.8.0
