### ISSUE TITLE
wrong time on chart component

### ISSUE THREAD

**Issue by guiguid** [lovasoa/SQLpage#324]
### Introduction

There is a gap in the time in SQLITE, and "chart" component ( True as TIME ).

### To Reproduce

List of steps to reproduce the behavior. Include the sql file you are using and the eventual relevant parts of your database schema

```sql
select 
dt                      as date
FROM balance
ORDER BY balance.dt DESC LIMIT 1;
-- RETURN
-- 2024-05-20 08:26:49
```
others component works  (timeline component) :
```sql
select 
    'timeline' as component,
    TRUE       as simple;
select 
    'Last Update at ' as title,
    dt                      as date
FROM balance
ORDER BY balance.dt DESC LIMIT 1;
```
![image](https://github.com/lovasoa/SQLpage/assets/71406/e855a8ff-cda7-44f0-a552-4b4174178403)

### Actual behavior

chart component display wrong time :
```sql
select 
    'chart'             as component,
    'Balance History' as title,
    'area'              as type,
    'indigo'            as color,
    5                   as marker,
    TRUE                as time;

select 
    dt as x,
    balance                     as y 
FROM balance
ORDER BY balance.dt DESC LIMIT 60;
```
![image](https://github.com/lovasoa/SQLpage/assets/71406/b41a3b68-70aa-4e3e-84cd-c77ba30d3090)

### Expected behavior
The time displayed by "chart" component should be the same as SQLITE and others components.

### Version information

 - OS: NixOS
 - Database :  SQLite
 - SQLPage Version : 0.20.5

### Additional context
Local Time: GMT +1 (Paris) + Summer.

### more
Thanks for this amazing tool!

**Comment by DSMejantel** [comment]
Bonjour,

You need ISO datetimes who are parsed and displayed in a readable format.
I use this expression : strftime('%Y-%m-%dT%H:%M:%fZ',date_created) as x
```
select 
    'chart' as component,
    'Historique du solde' as title,
    'area'  as type,
    'red'   as color,
    1 as marker,
    TRUE as time,
    1000 as ymax;   
select 
    strftime('%Y-%m-%dT%H:%M:%fZ',date_created) as x,
    printf("%.2f",(SUM(prix) OVER(order by date_created))) as y
    FROM finances; 
```

**Comment by guiguid** [comment]
Thanks, this hack works! 
![image](https://github.com/lovasoa/SQLpage/assets/71406/82a5a906-740d-4573-8c87-744b48259f02)

But the documentation should be updated if not internally fixed in sqlpage it self.

**Comment by DSMejantel** [comment]
Re,
C'est dans la documentation de SQLPage comme suggéré avec l'exemple 1.

![image](https://github.com/lovasoa/SQLpage/assets/149260856/34e6bbf1-a156-49be-b237-bdd65c3362e4)

Mais cela nécessite quelques connaissances dépassant SQLpage pour s'adapter  le cas échéant au format des données de sa base. Cela pourrait être rappelé avec un autre exemple.

**Comment by lovasoa** [comment]
Hello @guiguid, and welcome to SQLPage !
Out of curiosity: what is the application you are building ?

The provided datetime string does not have timezone information, and SQLPage interprets it as a local datetime, but displays it as UTC on the x axis by default. I do agree that this behavior is surprising and should be changed. 

The default behavior should be to display the data in the user's local timezone when no timezone info is provided. I will change that for the next version of SQLPage.

However, if I may give a piece of unsolicited advice: you probably should not store local datetime strings without timezone information in your database. Such strings are inherently ambiguous. You may want to store either a datetime string with timezone information (such as `2024-05-20 08:26:49+02:00`), or a much more concise unix timestamp ([`unixepoch()`](https://www.sqlite.org/lang_datefunc.html), `1716196946`)

**Comment by guiguid** [comment]
Hi @lovasoa ,
I write a little web frontend for a mining wallet.
remote host <-> ssh <-> periodic [nuShell](https://www.nushell.sh/) scripts for data processing (in and out) <-> SQLITE DB <-> SQLPage as Gui frontend.

As all my users are ( for now) in the same TZ, I basically store datetime in local time in SQLITE db (Yes, KISS for now...)  
```sql
CREATE TABLE balance (
    dt DATE DEFAULT (datetime('now','localtime')),
    ....
 );
```
I'll give a try to your advise.
Thanks

**Comment by lovasoa** [comment]
The behavior of SQLPage concerning x axes in time series plots was changed. 
You can have a look at the next (unreleased) version in lovasoa/sqlpage:main on docker.

**Comment by lovasoa** [comment]
Your app sounds cool! Do you have a link? Have you written about it?

**Comment by guiguid** [comment]
Not now. It's a private usage only, but I could write something about, that's a good idea.

**Comment by lovasoa** [comment]
I would love to read about it. And if you have pain points while learning SQLPage, I'm very interested in that too, I'm currently trying to simplify and clarify the website and documentation.

**Comment by guiguid** [comment]
I've point some unclear things:
- How to draw a multilines charts (the purpose of "series" is un clear for me , and I have not found examples.
- Is it possible to add a "cron" feature in order to execute a .sql at given time or delay? (Perhaps in the [file stored inside the DB](https://github.com/lovasoa/SQLpage?tab=readme-ov-file#hosting-sql-files-directly-inside-the-database) with an additional column ?)
- make  [file stored inside the DB](https://github.com/lovasoa/SQLpage?tab=readme-ov-file#hosting-sql-files-directly-inside-the-database) compatible with [sqlar](https://sqlite.org/sqlar/doc/trunk/README.md) native format. It makes easy to store sql file in db with no extra cost. Thanks SQLite ! ( just rename sqlpage_files to sqlar, and add 2 columns) . So update sql file in main SQLite DB will be as easy as : sqlite3 sqlpage/sslpage.db -Au *.sql
May I have to open issue for each items above ?
-
