### ISSUE TITLE
Error with 0.21 version on sqlpage.fetch function

### ISSUE THREAD

**Issue by ThierryM** [lovasoa/SQLpage#325]
Hi,
With "Ecole Inclusive" (SQLite database) running under SQLPage 0.21, I have a problem when I want to locate a school with the button "Ajouter depuis une carte" :
![Sélection_641](https://github.com/lovasoa/SQLpage/assets/1470067/a7f627b6-7b24-410f-8408-aa936c8c9bde)
Here the error message:
`Failed to set the $api_results variable to StmtWithParams { query: "SELECT CAST(? AS TEXT)", params: [FunctionCall(SqlPageFunctionCall { function: fetch, arguments: [GetOrPost("url")] })] }`
`Error in function call sqlpage.fetch($url).
Expected sqlpage.fetch(http_request)`
`Parameter http_request: Unexpected NULL value`
Regard

**Comment by DSMejantel** [comment]
Sorry, but the problem was in my code. I have found the error, the variable was not correctly send to the other page who display the map. The 0.21 version is not guilty !
