### ISSUE TITLE
search component

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#331]
Hi,

I would like to build a page with a lot of text, and I was wondering how to implement a search engine. Is it possible?

Thank you.

**Comment by amrutadotorg** [comment]
Thank you so much. I will try that. 
Os it also possible to refine the search via facets and filters?

**Comment by lovasoa** [comment]
Yes it is! You can use the form component for that too

**Comment by amrutadotorg** [comment]
That's awesome! If I encounter any issues, I will use the discussion page.
