### ISSUE TITLE
Preserve file name on file upload

### ISSUE THREAD

**Issue by djyotta** [lovasoa/SQLpage#333]
**_What are you building with SQLPage ?_**

I have a suite of apps I use to help me transfer data between devices.
* It's not for sharing secrets, it's for convenience only. Not recommended to paste and private info... 

ie, I can paste something from the clip board on my PC to the web form, and then scan the QR code on my phone.
OR, on a device without a camera, the codes are 5 base 32 digits (yes, I'm not worried about collisions) so it's easy to remember and type.

Here is the tools:
* https://shandan.one/clip - paste text to share
* https://shandan.one/goto - tiny URL
* https://shandan.one/upload - upload file to share

I formerly used python + bottle and rolled my own UI. This is fine.

I persisted clip/link/file to disk by naming it by it's base32 hash. Lots of small files. This is fine.

On finding out about SQLPage, I'm converting these so my website has a similar look and feel. Also want to get rid of the horrific python code I wrote.

It also make sense to store this stuff in db so it's easier to cleanup old data and apply size limits (had a bash script to do it, but ... yeah not comfortable with it).

**_What is your problem ? A description of the problem, not the solution you are proposing._**

The drawback with the SQLPage version is that I can not preserve the file name on upload.

My old UI, I was preserving the file name supplied by the browser:
```
-----------------------------4053620313313727090337127195
Content-Disposition: form-data; name="action"

Upload
-----------------------------4053620313313727090337127195
Content-Disposition: form-data; name="content"; filename="match.sh"
Content-Type: application/x-shellscript

#!/bin/bash
grep -ni 'import .*gnu' "$@"

-----------------------------4053620313313727090337127195--
```
The `Content-Disposition` header includes the filename (at least on Brave and Firefox).

_**What are you currently doing ? Since your solution is not implemented in SQLPage currently, what are you doing instead ?**_

There doesn't seem to be a way to get the filename out of the form data on SQLPage.

For now, I'm using the base32 code as the file name - at least this is not random and will be consistent on each download and also relates back to the code used to share the file.

_**Describe the solution you'd like**_

I'd like to preserve the file name on upload, so that when users download the file, the don't get a random or meaningless name.

A SQLPage function like [uploaded_file_mime_type](https://sql.ophir.dev/functions.sql?function=uploaded_file_mime_type#function) would be good. Maybe call it `uploaded_file_name`. Can return NULL if user-agent doesn't provide it.

**Comment by lovasoa** [comment]
Hi !
  Indeed, I agree we should have an `uploaded_file_name` function. It shouldn't be hard to add in [`functions.rs`](https://github.com/lovasoa/SQLpage/blob/main/src/webserver/database/sqlpage_functions/functions.rs). Do you want to have a stab at implementing it, and opening a PR ?

**Comment by djyotta** [comment]
OK, I'll have a go. I think I should do some basic programs in rust first though - I feel I do everything oddly in rust because I have no idea what is available in terms of libraries etc...

**Comment by lovasoa** [comment]
Don't hesitate to open even a awkward pull request, I'll be there to help !

**Comment by djyotta** [comment]
@lovasoa I've started looking at this. I see there is also a file size attribute too which would also be handy to have access to. So I'm wondering if instead we should have a ``uploaded_file_attributes`` returning JSON:
```json
{
  "name": "myfile.ext",
  "size": 1234,
  "content-type": "application/octet-stream",
  "path": "/path/to/file"
}
```

**Comment by lovasoa** [comment]
If rather have separate functions, for performance and convenience
