### ISSUE TITLE
allow calling sqlpage functions on all rows returned from a database query

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/SQLpage#337]
Currently sqlpage functions are executed before the query is sent to the database, and their output is sent to the database.
To use a value from the database as input in a sqlpage function, one needs to define a variable:

```sql
set $x = (select x from y where id = 123);
select sqlpage.some_function($x);
```

However, the following is not possible:

```sql
select sqlpage.some_function(x) from y;
```

we should lift this limitation.

see https://github.com/lovasoa/SQLpage/discussions/328

**Comment by lovasoa** [comment]
@guspower, @amrutadotorg, this is now fully implemented and works. Finally, starting in 0.25, you can do things like 

```sql
select 'dynamic' as component, 
    sqlpage.run_sql('display_product.sql', json_object('product_id', product_id)) as properties
from products;
```

**Comment by guspower** [comment]
hey this is great, very cool feature thank you @lovasoa
