### ISSUE TITLE
Button component doesn't have a row-level parameter ID 

### ISSUE THREAD

**Issue by bruceus** [lovasoa/SQLpage#340]
### Introduction

When the button component row-level parameter ID is defined, I cannot find it the rendered html code in SQLpage.

### To Reproduce

List of steps to reproduce the behavior. Include the sql file you are using and the eventual relevant parts of your database schema

```sql
select
	'button'	as component,
	'pill'		as shape;
select
	'arrow-big-up'	as icon,
	'btop'			as id,
	'#top'			as link;
```

### Actual behavior

When the SQLpage is rendered, I'm looking into the html code via Chrome Developer tools and I cannot see any ID within the DIV html tag for button. 

No errors generated in SQLpage.

### Screenshots
<img width="1080" alt="2024-05-24_11-45-35" src="https://github.com/lovasoa/SQLpage/assets/18512522/eb316e37-fcfd-47d3-bba1-0a07ad2b53b9">

### Expected behavior
The ID is present within DIV html tag.

### Version information

 - OS: Windows
 - Database Not important
 - SQLPage Version [found when hovering the default footer of pages]: 0.20.5

### Additional context
I cloned the latest SQLPage code from GIT.
I had a look into sqlpage\templates\button.handlebars and I cannot find ID there.

**Comment by lovasoa** [comment]
Hello and welcome to SQLPage! 
The row level attributes of the button component are documented here: https://sql.ophir.dev/documentation.sql?component=button#component

 There is indeed no id attribute. But that would be a welcome addition! Would you be interested in making a small pull request to add this?


And out of curiosity: what is it that you are building with SQLPage?

**Comment by bruceus** [comment]
> Hello and welcome to SQLPage! The row level attributes of the button component are documented here: https://sql.ophir.dev/documentation.sql?component=button#component
> 
> There is indeed no id attribute. But that would be a welcome addition! Would you be interested in making a small pull request to add this?
> 
> And out of curiosity: what is it that you are building with SQLPage?

Hi there,
Sorry, I was mistaken with ID in DIV html tag placement. Only the top-level parameter should be included within DIV html tag.

I am trying to add "Scroll-up" button which I find useful for navigating user on the long pages with many SQL rows to the top of the page and I need to place it somewhere on the SQLpage. I'm currently testing the simplest placement which is the fixed one by referencing main.css file in shell component with the following code:
`
#btop {
position: fixed;
bottom: 0;
right: 10px;
font-size: 40px;
z-index: 9999;
}
`

The issue is that even if I tried to add id as the row-level attribute in button.handlebars within A html tag like this:
`
<div class="btn-list mb-2 {{#if justify}}justify-content-{{justify}}{{/if}} {{class}}">
{{#each_row}}
    {{#if form}}
    <button type="submit" form="{{form}}" {{#if link}}formaction="{{link}}"{{/if}} 
    {{else}}
    <a{{#if id}} id="{{id}}"{{/if}} href="{{link}}"
    {{/if}}
        class="btn {{#if disabled}} disabled{{/if}}
        {{~#if color}} btn-{{color}}{{/if}}
        {{~#if ../size}} btn-{{../size}}{{/if}}
        {{~#if outline}} btn-outline-{{outline}}{{/if}}
        {{~#if ../shape}} btn-{{../shape}}{{/if}}
        {{~#if space_after}} me-auto{{/if}}"
        role="button">
        {{~#if icon~}}
            <span class="me-1">{{~icon_img icon~}}</span>
        {{~/if~}}
        {{~title~}}
    {{#if form}}
    </button>
    {{else}}
    </a>
    {{/if}}
{{/each_row}}
</div>

`
and reloaded the SQLpage, the button itself is placed where it should be but it looks a bit messy:
<img width="1005" alt="2024-05-24_13-10-27" src="https://github.com/lovasoa/SQLpage/assets/18512522/313a5c9b-ad39-4f5f-ab3b-6f1d72c13ec2">

Thank you for the generous offer to create a pull request.
Gladly, but the problem is that my button looks best if the ID was placed in the code as the top-level attribute within DIV html tag which is probably very specific to my case and not applicable to all cases (e.g. 3 buttons case from the documentation).
If it is added as the row-level attribute into the A attribute to comply with SQLPage documentation it is a mess. I was just playing with the default button.handlebars where only the A html tag is available for building the button.
