### ISSUE TITLE
dependency analysis

### ISSUE THREAD

**Issue by setop** [lovasoa/SQLpage#35]
I have had an alert from my antivirus on sqlpage.exe file.

It's probably low risk but I cloned the repo to see [dependabot report](https://github.com/lovasoa/SQLpage/network/dependencies).

![See](https://pic.infini.fr/NK8VpsLF/MOppir9N.png)

It found some vulnerable dependencies : libsqlite3-sys/0.24.2 and time/0.1.45 

Maybe worth activate dependabot.

**Comment by lovasoa** [comment]
Hello and thank you for opening this issue !

The SQLPage project takes security very seriously. Dependabot  is already activated in this repository, and every relevant issue is acted upon quickly. Both vulnerabilities (in libsqlite and time) are not relevant in the context of SQLPage. You can read more about them here

 - https://blog.trailofbits.com/2022/10/25/sqlite-vulnerability-july-2022-library-api/
 - https://github.com/time-rs/time/security/advisories/GHSA-wcg3-cvx6-7396
 
It is very common for an anti-virus to raise alerts about software they don't recognize. You should contact your anti-virus manufacturer about the false positive.

**Comment by lovasoa** [comment]
This commit updates sqlx, and transitively libsqlite3-sys: https://github.com/lovasoa/SQLpage/commit/cbe9b2308ad26663bb248778dde687daa72df425

libsqlite3-sys is now on its latest version, which should fix the false positive alert from vulnerability scanners
