### ISSUE TITLE
make link_text in hero component mobile friendly 

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#350]
Hi, is it possible to make `link_text` mobile friendly? With long text it does not fit. Thank you.

![Screenshot 2024-05-30 at 00 59 26](https://github.com/lovasoa/SQLpage/assets/38246728/44e37888-6ad3-4709-9f96-03eb79e6f94d)

```
SELECT 'hero' as component,
    'Nirmala Vidya' as title,
    'Build **Your Self Knowledge** Effortlessly with **Lectures of Shri Mataji Nirmala Devi**' as description_md,
    'Kundalini Rise Animation with music_EN.webm' as video,
    'https://www.amruta.org/self-realisation/' as link,
    'New to Sahaja Yoga? Then first get your Self Realisation here.' as link_text;
```

**Comment by lovasoa** [comment]
Yes, you can add the text-wrap class to the button. Can you open a new pull request?

**Comment by amrutadotorg** [comment]
sure, should I do it here?
[https://github.com/lovasoa/SQLpage/blob/main/sqlpage/templates/button.handlebars](https://github.com/lovasoa/SQLpage/blob/main/sqlpage/templates/button.handlebars)
