### ISSUE TITLE
white background on dark mode with embed

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#351]
Hi, is it possible to remove/fix the white background when using embed in dark mode?
thank you 

![Screenshot 2024-05-30 at 07 28 59](https://github.com/lovasoa/SQLpage/assets/38246728/f9cda738-abf7-46fd-99ad-f3ebdf028b4e)

```sql
SELECT 'card' AS component, 1 AS columns;
SELECT
    'https://player.vimeo.com/video/951425265?h=debe29aecf' AS embed,
    'autoplay; fullscreen; picture-in-picture; clipboard-write' AS allow,
    'iframe' AS embed_mode,
    '700' AS height;
```

**Comment by lovasoa** [comment]
Hello ! The white background you can see is displayed by vimeo, not by SQLPage.

Vimeo offers the option to make this background black if you want: https://help.vimeo.com/hc/en-us/articles/12426260232977-Player-parameters-overview

```sql
select 'shell' as component, 'dark' as theme;
SELECT 'card' AS component, 1 AS columns;
SELECT
    'https://player.vimeo.com/video/951425265?transparent=0' AS embed,
    'autoplay; fullscreen; picture-in-picture; clipboard-write' AS allow,
    'iframe' AS embed_mode,
    '700' AS height;
```

**Comment by amrutadotorg** [comment]
Thanks, it worked with transparent=0

```
SELECT
    'https://player.vimeo.com/video/951425265?transparent=0' AS embed,
    'autoplay; fullscreen; picture-in-picture; clipboard-write;' AS allow,
    'iframe' AS embed_mode,
    '700' AS height;
```
    
is it possible to pass the `style="background-color: #FFFFFF"` ?

Example embed code:

`<iframe src="https://player.vimeo.com/video/951425265" style="background-color: #FFFFFF" width="1000" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`
