### ISSUE TITLE
The "separator" parameter of the CSV component does not work

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/SQLpage#352]
### Discussed in https://github.com/lovasoa/SQLpage/discussions/345

<div type='discussions-op-text'>

<sup>Originally posted by **ThierryM** May 28, 2024</sup>
Hi,
I would download data from SQLpage with ";" separator but I don' succeed. The .csv file obtained has the "," as separator.
My code to export is :
`SELECT 
    'csv' as component,
    'Exporter le fichier des établissements ' as title,
    'etablissements' as filename,
    'file-download' as icon,
    'green' as color,
    ';' as separator;`
Where is my mistake ?
Thanks for your help.</div>

**Comment by mnesarco** [comment]
I have the same problem
