### ISSUE TITLE
highlighting the search term FTS PostgreSQL 

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#358]
Hi, is there a way to highlight the words using FTS in PostgreSQL?

thank you

![Screenshot 2024-05-31 at 11 43 46](https://github.com/lovasoa/SQLpage/assets/38246728/cbde01ad-fbac-4922-9a2a-e2aeef032e4d)

```

SELECT 
    'text' AS component;

SELECT post.id, 
       ts_headline('english', post.content, plainto_tsquery('english', $search), 'StartSel=<mark>, StopSel=</mark>') AS contents,
       translations.language_code
FROM post
JOIN translations ON translations.element_id = post.id
  AND translations.element_type = 'post_post'
  AND translations.language_code = 'en'
WHERE post.content_tsv @@ plainto_tsquery('english', $search);
```

**Comment by lovasoa** [comment]
You can use the StartSel and StopSel  options of the ts_headline function to make postgres return search results highlighted in markdown, and then use the description_md row-level parameter to display the resulting markdown text. 

https://www.postgresql.org/docs/current/textsearch-controls.html

**Comment by amrutadotorg** [comment]
Thank you. I think I was not precise enough. I would like to use a color for highlighting.

**Comment by lovasoa** [comment]
That is not possible with the built-in components, but you have two possibilities: 
 - can create your own component, specific to your application that will display raw html :/https://sql.ophir.dev/custom_components.sql
 - add a custom css stylesheet from the shell component to style bold text the Way you need inside results, and use markdown to display search terms as bold text

**Comment by amrutadotorg** [comment]
Thank you for the ideas.
