### ISSUE TITLE
Make the application independent from external CDN when self-hosted

### ISSUE THREAD

**Issue by nanawel** [lovasoa/SQLpage#37]
Currently even with a self-hosted instance on a private area, there are still requests sent outside because of the dependency to `tabler-icons` and Google Fonts.

It's hardcoded in `sqlpage/templates/shell.handlebars` so there's no easy way to prevent it, unless overriding the component I guess.

https://github.com/lovasoa/SQLpage/blob/9c781dc593c3362b6dd24128d3b8eef744b80509/sqlpage/templates/shell.handlebars#L6-L22

Do you think you could add a way to make all dependencies (current and the ones to come) self-hostable too?
I'm not saying this should be the default behavior, but it would be very handy to have a defined procedure to replace CDN with custom URLs.

**Comment by lovasoa** [comment]
Yes, I do want to bundle the icons in the executable, but still haven't got to it :)

**Comment by lovasoa** [comment]
Yes, you can override it for your app ! You don't need the `static_path` handlebar helper at all, it's just the thing that adds the content hash at the end of files (`ee38880ed0dee496` in `sqlpage.ee38880ed0dee496.css`). Just hardcode the path.

Just hardcode `<link rel="stylesheet" href="/tabler-icons.min.css" />` and put `tabler-icons.min.css` at the root of your website.

**Comment by nanawel** [comment]
My bad! It didn't work because I made a mistake in the path.
I prefer to use the existing `css/` directory for all CSS files, it seems most appropriate. So the code is
```html
<link rel="stylesheet" href="/css/tabler-icons.min.css">
```
(it does not handle a custom base path but it's another story)
