### ISSUE TITLE
The links on the page https://sql.ophir.dev/examples/layouts.sql do not work

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#374]
Hi, please check the page [https://sql.ophir.dev/examples/layouts.sql](https://sql.ophir.dev/examples/layouts.sql) the links do not work.

**Comment by lovasoa** [comment]
:grimacing: ! Thanks for reporting this !

The bug was introduced in https://github.com/lovasoa/SQLpage/commit/848a49df31991efa04a8ec424c0bc7d96ea1ed08#diff-98879de122229a6bf50906cf544797b856f71ae000226141c718b105d41c2be4

**Comment by lovasoa** [comment]
We should use https://sqlite.org/json1.html#jpatch to apply the layout on top on the `properties FROM example`
