### ISSUE TITLE
icons are not displayed when serving from a subpath

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/SQLpage#377]
When setting `site_prefix` in the configuration, icons are not displayed.

The bug is in this line, that should include the site prefix:

https://github.com/lovasoa/SQLpage/blob/f6b326f8c5d9e52999ed12264142ec29054b8724/src/template_helpers.rs#L323

@djyotta , you are probably affected by this.

**Comment by djyotta** [comment]
Not currently. I haven't migrated to site-prefix yet. Plus I don't use the icons yet so I wouldn't be affected.
Thanks for the heads up though.
