### ISSUE TITLE
Zoom in the map component does not work?

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#378]
Hi, while developing the page with the map component, I found that the zoom attribute does not work if the second select statement is present. Is this intentional?

thank you

![Screenshot 2024-06-06 at 12 33 40](https://github.com/lovasoa/SQLpage/assets/38246728/b4ffda7f-4e3e-4f8a-acc7-c25192d294c5)

```
select 
    'map'   as component,
    'New Delhi-1' as title,
    28.6139     as latitude,
    11     as zoom,
    77.209      as longitude;
```

```
select 
    'map' as component,
    'New Delhi-2  ' as title,
    11     as zoom;
select 
    28.6139     as latitude,
    77.209      as longitude;
```

**Comment by lovasoa** [comment]
Hello ! 
  I think there is a confusion here. The zoom level **is the same** on both your screenshots. The attribute `11 as zoom` did work in both cases. The only difference is in where the map is centered. In the first example, you provided latitude and longitude as top-level attributes, so the map is centered at the place you specified.

![image](https://github.com/lovasoa/SQLpage/assets/552629/60b43bd8-1a1c-4dfb-bb2c-4d69fa5adddb)

In the second example, you did not provide a latitude and longitude as top level attributes, so the map is still zoomed to zoom level 11, but centered on "lat=48,lng=3" (the default value when no top-level latitude and longitude are provided).

The second query adds pins to the map, and in the second example, if you manually center the map on New Dehli, you'll see that the point was successfully created.

In the end, what you want is probably to specify both top-level and row-level coordinates to create a pin and center the map on it:

```sql
select 
    'map'   as component,
    'New Delhi-3' as title,
    11     as zoom,
    28.6139     as latitude,
    77.209      as longitude;
select 
    28.6139     as latitude,
    77.209      as longitude;
``` 

![Screen Shot 2024-06-07 at 08 00 43](https://github.com/lovasoa/SQLpage/assets/552629/baa1bbe3-1ccc-4a1c-9a1d-6f184d76242e)

**Comment by lovasoa** [comment]
I updated the default behavior to remove the default centering on "lat=48,lng=3" which was confusing. Now when top-level coordinates are omitted, the map centers on the pins that you add to it.

Now this

```sql
select 
    'map'   as component,
    'New Delhi-1' as title,
    28.6139     as latitude,
    11     as zoom,
    77.209      as longitude;

select 
    'map' as component,
    'New Delhi-2  ' as title,
    11     as zoom;
select 
    28.6139     as latitude,
    77.209      as longitude;


select 
    'map'   as component,
    'New Delhi-3' as title,
    28.6139     as latitude,
    11     as zoom,
    77.209      as longitude;
select 
    28.6139     as latitude,
    77.209      as longitude;

select 
    'map'   as component,
    'New Delhi-4' as title,
    28.6139     as latitude,
    77.209      as longitude;
```

displays like that:

![image](https://github.com/lovasoa/SQLpage/assets/552629/cdf5dc89-6031-44d1-8a22-51efc3761845)

**Comment by amrutadotorg** [comment]
awesome, thank you for the explanation
