### ISSUE TITLE
in the hero component the image disappears on mobile

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#380]
Hi,

When I switch to mobile view then the image disappears.

`SELECT 'hero' as component, '"I bow to all the seekers of truth."' as title, '/media/shri_mataji_pp_namaste.jpg' as image;
`

you can test it here:
[https://pp.amruta.org/](https://pp.amruta.org/)

thank you

**Comment by amrutadotorg** [comment]
replaced with the video and it works fine

**Comment by lovasoa** [comment]
Could you please provide instructions on how to reproduce the issue in chrome dev tools ?

I tried to reproduce the iPhone mini viewport, I still the image in the hero component:

![image](https://github.com/lovasoa/SQLpage/assets/552629/f06a753c-88bc-48a7-947e-98ae66237dac)

**Comment by amrutadotorg** [comment]
I had the bug in the code. Everything works fine.
