### ISSUE TITLE
Linux binary and ARM CPU - failed to run

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#382]
Hi,

Today I tried to run the `sqlpage.bin` file on AWS Graviton 64-bit ARM (Debian 12), but it failed. However, compiling from the source code worked. If the distributed Linux binary was compiled for x86, it would be helpful to mention this in the documentation.

**Comment by lovasoa** [comment]
I added a note in the README, hopefully it helps: https://github.com/lovasoa/SQLpage/commit/2b0ad00ba8790597293bb4c5860035c4ac2e740f

**Comment by amrutadotorg** [comment]
I would suggest to rename the package with linux to 
`sqlpage-linux-x64.tgz
`
so in future :) we might add for example:
```
sqlpage-linux-arm64.tgz
sqlpage-linux-armv7l.tgz
```
