### ISSUE TITLE
Request to Add Essential Meta Properties for Rich Previews

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#392]
Hi, I'd like to request adding some essential meta properties to the `<head>` section via the `shell` component. These properties are necessary to enable "rich previews" or "link previews" when the website's links are shared.

```
    <meta property="og:title" content="Your Website Title">
    <meta property="og:description" content="Description of your website">
    <meta property="og:image" content="URL of the image you want to display">
    <meta property="og:url" content="URL of your website">
    <meta property="og:type" content="website">
```

These properties will ensure that platforms like social media or messaging apps can generate previews with a title, description, and image when our website's links are shared.

Could we please implement this for all users?

Thank you!

EDIT
some of them (description, title ...) are already present in the shell component, so we could use them

**Comment by lovasoa** [comment]
We do have a meta description available already.
The title and URL are taken from the webpage by default; do you have an use case where you need to customize them ? Or change the `og:type` ?

The ne thing that I think could be a good idea to add is `og:image`. Do you want to open a pull request for it ?

**Comment by lovasoa** [comment]
Most platforms just use the page title and description anyway, no need for og tags for them

**Comment by amrutadotorg** [comment]
Done #393

**Comment by lovasoa** [comment]
fixed by https://github.com/lovasoa/SQLpage/pull/393
