### ISSUE TITLE
Misleading docs and form field type "number"

### ISSUE THREAD

**Issue by pchemguy** [lovasoa/SQLpage#401]
The "form" component docs indicates that a field of type "number" accepts only numbers. In fact, it only accepts **whole** numbers. At the very least, I would expect that the docs should be updated to clarify this matter.

**Comment by lovasoa** [comment]
Hi! You can use the 'step' property to control the precision of numbers entered into the field. It is indeed 1 by default, but you can set it to 0.01 and you will be able to set your input to a floating point number.

**Comment by pchemguy** [comment]
I see, thank you
