### ISSUE TITLE
date type datetime is displayed as gibberish

### ISSUE THREAD

**Issue by f8dca** [lovasoa/SQLpage#41]
MSSQL datetime data 2023-06-06 00:00:00.000 shows as  �

**Comment by lovasoa** [comment]
What is the exact mssql type of the datetime you are selecting ? 

SQL Server has many datetime types

![image](https://github.com/lovasoa/SQLpage/assets/552629/7539d66d-8991-4de3-9354-c67535b6c3db)

**Comment by f8dca** [comment]
The mssql data type was **datetime**

'''sql
select count(*) as Y, cast(invoice_date as datetime) as X
from AMTV2.SPIRE_SALES_HISTORY_ITEMS
group by  invoice_date
'''

**Comment by lovasoa** [comment]
Okay. I implemented support for datetime in the latest sqlx-oldapi. But datetime is deprecated, you should use datetime2 or datetimeoffset.

**Comment by lovasoa** [comment]
Okay, the bug was actually in SQLPage. Working on it!

**Comment by lovasoa** [comment]
I updated the title because the issue was not specific to mssql. It'll be fixed in the next version.

**Comment by lovasoa** [comment]
Fixed in https://github.com/lovasoa/SQLpage/releases/tag/v0.9.2
