### ISSUE TITLE
Add Tooltip Property for Icon in DataGrid Component

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#425]
I would like to request the addition of a tooltip feature that displays when the cursor is hovered over an icon within the card component.

Use Case
In my specific use case, the text might be in draft mode, and I need to provide users with additional context or instructions. For example, I want to inform users to be extra careful while reading the transcript.

Proposed Solution
Implement a tooltip that appears when the user hovers over the icon. The tooltip should be customizable, allowing developers to specify the tooltip text according to their needs.

Example
When a user hovers over an icon, a tooltip should appear with a message like "Draft mode: Please review carefully."

![Screenshot 2024-06-19 at 05 03 11](https://github.com/lovasoa/SQLpage/assets/38246728/0f82e0ff-732d-4017-a023-d3bc585abe39)

**Comment by lovasoa** [comment]
Good feature! Do you think the tooltip should appear only on the icon? It would probably be more logical to have a tooltip over the entire element. 

Pull request welcome!

**Comment by amrutadotorg** [comment]
great idea, so it will be a top-level parameters
