### ISSUE TITLE
No DATABASE_URL, using the default sqlite database './sqlpage.db'

### ISSUE THREAD

**Issue by althaf004** [lovasoa/SQLpage#43]
We have created a json file in 'sqlpage/sqlpage.json'

```
{
  "database_url": "postgres://postgres:ci123@10.10.11.242:5432/althaf",
  "max_database_pool_connections": 25,
  "database_connection_idle_timeout_seconds": 60,
  "database_connection_max_lifetime_seconds": 3600,
  "sqlite_extensions": [],
  "port": 8082
}
```

But still the error comes as "No DATABASE_URL, using the default sqlite database './sqlpage.db'"

**Comment by lovasoa** [comment]
Hello, and welcome to sqlpage :slightly_smiling_face: 

Can you show for file hierarchy, and how you are launching the sqlpage binary ? Maybe share a screenshot ?

The path `sqlpage/sqlpage.json` must be relative to the current working directory where you launch the sqlpage executable.

**Comment by lovasoa** [comment]
A quick example from my computer : 

```sqlpage on  main is 📦 v0.9.0 via 🦀 v1.71.0 took 5s 
❯ cat > sqlpage/sqlpage.json 
{
  "database_url": "postgres://postgres:ci123@10.10.11.242:5432/althaf",
  "max_database_pool_connections": 25,
  "database_connection_idle_timeout_seconds": 60,
  "database_connection_max_lifetime_seconds": 3600,
  "sqlite_extensions": [],
  "port": 8082
}

sqlpage on  main [!?] is 📦 v0.9.0 via 🦀 v1.71.0 
❯ ./sqlpage.bin 
[2023-07-31T10:19:03Z INFO  sqlpage::webserver::database] Connecting to database: postgres://postgres:ci123@10.10.11.242:5432/althaf
```

**Comment by althaf004** [comment]
hey lovasoa, i had made a mistake in storing the json file in folder structure.  I had placed in correctly and the issue is fixed. Thanks for your quick headsup.
