### ISSUE TITLE
Do not trim the text in the card  component (mobile)

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#437]
![image](https://github.com/lovasoa/SQLpage/assets/38246728/4e97df6c-f833-427d-aae3-49459e67a8b7)

Hi. I would suggest to remove the trim option for the row contents in the card component (for mobile version). Attaching example. 

Thank you

**Comment by lovasoa** [comment]
I don't think it shoud be the default, but we could have an option to wrap the text. Do you want to make a pr ?

**Comment by amrutadotorg** [comment]
How about introducing a top-level parameter `wrap` of type `bool`? If `wrap` is set to `true`, then all `description` & `description_md`  parameters at both the top level and row level will be wrapped.

**Comment by lovasoa** [comment]
Yes, that would be good

**Comment by amrutadotorg** [comment]
Great. Do we have already a css class for that?

For example we could use it like that:

`{{#if description_md}}
    {{#if wrap}}
        <div class="wrapped">{{{markdown description_md}}}</div>
    {{else}}
        {{{markdown description_md}}}
    {{/if}}`

**Comment by lovasoa** [comment]
Yes, we have the `text-wrap` class

![image](https://github.com/lovasoa/SQLpage/assets/552629/458ae32f-7f31-4dc3-9638-61673088dad2)

**Comment by amrutadotorg** [comment]
thank you, I tired this, but it does not work. Have no other ideas.

```
{{#if title}}
    <h2 class="mt-3 mb-0">{{title}}</h2>
{{/if}}
{{#if description}}
    {{#if wrap}}
        <p class="text-wrap">{{description}}</p>
    {{else}}
        <p>{{description}}</p>
    {{/if}}
{{/if}}
```

**Comment by lovasoa** [comment]
I implemented it

**Comment by amrutadotorg** [comment]
Ahh I modified card component instead of a list component:)
