### ISSUE TITLE
Environmental variable naming convention proposal

### ISSUE THREAD

**Issue by f8dca** [lovasoa/SQLpage#44]
I think the [environmental variable names](https://github.com/lovasoa/SQLpage/blob/main/configuration.md) for SQLPage are way to generic and prone for collision with other applications.

Maybe **sqlpage_envname** format would be a better choice. 
Another benefit of this approach would be that when the variables listed they would be grouped together by default.

**Comment by lovasoa** [comment]
I just pushed v0.10.0 which implements that
