### ISSUE TITLE
Page title trimmed or not visible.

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#446]
Hi,

I've noticed an issue with the visibility of the menu on different screen sizes. In some cases, the page title is either not visible or gets trimmed.

You can see the issue here: [learnsahajayoga.org](https://learnsahajayoga.org/)

trimmed:
![Screenshot 2024-06-22 at 12 00 01](https://github.com/lovasoa/SQLpage/assets/38246728/7a8cdacf-9b48-41cf-91b8-42b091c4cfa5)

not visible:
![Screenshot 2024-06-22 at 11 59 47](https://github.com/lovasoa/SQLpage/assets/38246728/e6f739ce-7dde-405a-9fb6-aa5173497f88)

**Comment by lovasoa** [comment]
What do you think would be the right behavior when the title is too long for everything to fit?

**Comment by amrutadotorg** [comment]
Hiding whole title might be the best option, but trimming does not look good (even if icon is added), so maybe in both cases SQLPage should hide the title instead of trim it? 
![Screenshot 2024-06-22 at 12 33 21](https://github.com/lovasoa/SQLpage/assets/38246728/5e19a34c-0025-4c94-9912-818c65d3f235)
