### ISSUE TITLE
Bad query results

### ISSUE THREAD

**Issue by pchemguy** [lovasoa/SQLpage#452]
Evaluating files containing just the following:

| Input | Processed | Result | Correct? |
|--|--|:--:|:--:|
| SELECT NULL IS NULL; | NULL IS NULL | 1 | :heavy_check_mark: |
| SELECT lower(NULL) IS NULL; | LOWER(NULL) IS NULL | 0 | :x: |
| SELECT json(NULL) IS NULL; | JSON(NULL) IS NULL | 1 | :heavy_check_mark: |
| SELECT CAST(NULL AS TEXT) IS NULL; | CAST(NULL AS TEXT) IS NULL | 1 | :heavy_check_mark: |
| SELECT $_locale_code IS NULL; | CAST(? AS TEXT) IS NULL | 1 | **OK** |
| SELECT lower($_locale_code) IS NULL; | LOWER(CAST(? AS TEXT)) IS NULL | 0 | **BAD** |

**Comment by lovasoa** [comment]
@pchemguy , there was an issue with our builtin `lower()` function. It's fixed now.
