### ISSUE TITLE
Search in Table component not working for string containing a minus sign

### ISSUE THREAD

**Issue by f8dca** [lovasoa/SQLpage#46]
![image](https://github.com/lovasoa/SQLpage/assets/49892958/a47c2492-55cb-403a-a3a5-5e194a20277c)

**Comment by lovasoa** [comment]
@f8dca : It looks like the issue comes from here: https://github.com/javve/list.js/issues/699 

I'll see what I can do.

**Comment by lovasoa** [comment]
Fixed in https://github.com/lovasoa/SQLpage/releases/tag/v0.9.3
