### ISSUE TITLE
In the "PostGIS - using sqlpage with geographic data" example, no points with latitude 0 are shown. 

### ISSUE THREAD

**Issue by matthieupeeters** [lovasoa/SQLpage#462]
### Introduction

When adding points to the "PostGIS - using sqlpage with geographic data" example, when adding a point with latitude 0 it is ignored. 

Points with any other latitude are shown. 

Example fix at the end of the report. 

### To Reproduce

- Run the example code. 
- Add a point with lat/long 0 0,

### Actual behavior

The point will not show up on the map.

### Expected behavior

The point with lat/long 0 0 shows up on the map

### Version information

 - OS: Windows
 - Database Postgres
 - SQLPage Version: 0.24.1

### Additional context

The map.handlebars template has a bug which filters out latitudes of 0. A fix is in the fork here:

https://github.com/matthieupeeters/SQLpage.bugfixes

PR here:
https://github.com/lovasoa/SQLpage/pull/463

**Comment by lovasoa** [comment]
Thanks for both reporting and fixing this !

https://github.com/lovasoa/SQLpage/pull/463
