### ISSUE TITLE
Support for DECLARE and SET statements on mssql to use scalar functions

### ISSUE THREAD

**Issue by f8dca** [lovasoa/SQLpage#49]
Would it be possible to add support to declaring local SQL variables and setting their value ?
something along these lines:

```sql
declare @max_inv varchar(10) ;
set  @max_inv = func_getMaxInv(); --this is a scalar function to get the latest invoice number

SELECT 'table' as component

select [id] , [invoice_no], [invoice_date], [cust_no] 
from SALES_HISTORY 
where invoice_no = isnull($invoice_no, @max_inv)
```

This snippet should either show the invoice passed in the parameter or the last one.

**Comment by lovasoa** [comment]
That would indeed be nice ! But this will require support from [`sqlparser-rs`](https://github.com/sqlparser-rs/sqlparser-rs) first. Let's ask them !

**Comment by lovasoa** [comment]
In your particular example, is there a reason you cannot use 

```sql

select [id] , [invoice_no], [invoice_date], [cust_no] 
from SALES_HISTORY 
where invoice_no = isnull($invoice_no, func_getMaxInv())
```

?

**Comment by f8dca** [comment]
Yes, I can do that as workaround in this particular case. In amore generic way I still would love to be able to use local variables so there is no need to call a function many times.

**Comment by lovasoa** [comment]
Let's keep that open to keep track of the feature. It's something I'd like to see in SQLPage too

**Comment by lovasoa** [comment]
`SET` is supported as of 0.12.0-beta, and implemented on sqlpage's side (the variable are stored in sqlpage, not in the database). 

This allows for new interesting use cases, using variable values as inputs to sqlpage functions.
