### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by accforgithubtest** [lovasoa/SQLpage#50]
Loving this project !

Are there any plans to support Dark Mode in UI ?
I think having dark mode will be a killer feature.

Thanks !

**Comment by lovasoa** [comment]
Hi! The overall theme is provided by tabler, which does support dark mode, so it shouldn't be too hard to do. 

The first thing you can do is customize your own shell component locally. Create a shell.handlebars file in sqlpage/templates. 

Copy the official shell, and switch to [tabler's dark mode](https://github.com/tabler/tabler/issues/241) by adding the tabler-dark theme on the body. 

If it works well, you can open a pull request here to add an option in the shell template for dark mode.

**Comment by lovasoa** [comment]
My mistake, it looks like it's not `class="theme-dark"`, but `data-bs-theme="dark"`

![image](https://github.com/lovasoa/SQLpage/assets/552629/07973983-cd24-4c2a-aab3-8c646119bb82)

@accforgithubtest , do you want to make the small PR ?

It could be as simple as adding

```handlebars
{{#if dark}}
   data-bs-theme="dark"
{{/if}}
```

to `shell.handlebars`

**Comment by lovasoa** [comment]
done :confetti_ball: :heavy_check_mark: 

This will be in the next version.
