### ISSUE TITLE
[Postgres] Multi-column update seems not supported

### ISSUE THREAD

**Issue by anayrat** [lovasoa/SQLpage#500]
### Introduction

Postgres supports multi-column update:

https://www.postgresql.org/docs/current/sql-update.html

> Use the alternative column-list syntax to do the same update:
 > `UPDATE weather SET (temp_lo, temp_hi, prcp) = (temp_lo+1, temp_lo+15, DEFAULT)   WHERE city = 'San Francisco' AND date = '2003-07-03';`

### To Reproduce

```sql
UPDATE toto SET (c1,c2) =(42,42);
```
Is wrongly translated by :

```sql
UPDATE toto SET c1.c2 = (42, 42);
```

### Version information

 - OS: lin x
 - Database Postgres 16
 - SQLPage Version : 0.24.0

**Comment by anayrat** [comment]
It is even worse, even a simple UPDATE do not work:
```sql
UPDATE toto SET set c1 = 42;
```

Results in:
```
Failed to execute SQL statement:
UPDATE toto SET set.c1 = 42;
                 ⬆️
line 1, character 17
```

**Comment by anayrat** [comment]
Oh, it seems  duplicate of https://github.com/lovasoa/SQLpage/issues/403

**Comment by lovasoa** [comment]
Yes! You can try the latest builds for the yet unreleased v0.25 (on docker hub for instance), and everything should be working fine.
