### ISSUE TITLE
v0.25.0 deployment to official site failed

### ISSUE THREAD

**Issue by edgrip** [lovasoa/SQLpage#502]
### Introduction

It seems v0.25.0 deployment failed today

### To Reproduce

N/A

### Actual behavior

Github Action triggered the website deployment but dokku deployment log (Push to dokku, line 120) show v0.24.0 being started:

`remote:        [2024-07-13T06:23:10.461Z INFO  sqlpage] SQLPage v0.24.0 started successfully.`

https://sql.ophir.dev/documentation.sql shows v0.24.0 as version number

https://sql.ophir.dev/blog.sql shows error Invalid function call: sqlpage.link(COALESCE(external_url, ''), CASE WHEN external_url IS NULL THEN json_object('post', title) ELSE NULL END): Unknown function "link".

### Expected behavior
v0.25.0 running on official site :)

**Comment by lovasoa** [comment]
It's fixed. Thanks for reporting!

The version update on the server is not yet automated.
