### ISSUE TITLE
Support for MacBook Air (M1, 2020)

### ISSUE THREAD

**Issue by spinning-fantasies** [lovasoa/SQLpage#51]
I wanted to install SQLPage on my MacBook Air (M1, 2020) and I had an error message trying to extract the archive :

<img width="385" alt="Capture d’écran 2023-08-08 à 12 35 59" src="https://github.com/lovasoa/SQLpage/assets/133113709/c16f6893-6113-4ee3-8217-73d425c4a81e">

Could you provide some help on this ?

Many Thanks,

--
Mathieu

**Comment by lovasoa** [comment]
Hi! The easiest is probably to install SQLPage with homebrew:

https://brew.sh/
https://formulae.brew.sh/formula/sqlpage#default

```
brew install sqlpage
```

**Comment by spinning-fantasies** [comment]
It works !
