### ISSUE TITLE
Issue Rendering Tables (javascript error Uncaught TypeError: t.list is undefined)

### ISSUE THREAD

**Issue by guspower** [lovasoa/SQLpage#513]
### Introduction

Some tables are not rendering and only have the loading spinner active.

### To Reproduce

I am loading multiple series from a jsonb payload. This works when running locally but not when deployed on a vm behind an nginx proxy. The code is identical (both cloned from same git repo). 

### Actual behavior

The table never gets beyond showing the spinner. There are console errors in Firefox:

```
Uncaught TypeError: t.list is undefined
    i https://ivz.infinitesidequests.com/sqlpage.ae8abf722876661d.js:16
    e https://ivz.infinitesidequests.com/sqlpage.ae8abf722876661d.js:16
    e https://ivz.infinitesidequests.com/sqlpage.ae8abf722876661d.js:16
    exports https://ivz.infinitesidequests.com/sqlpage.ae8abf722876661d.js:16
    start https://ivz.infinitesidequests.com/sqlpage.ae8abf722876661d.js:16
    exports https://ivz.infinitesidequests.com/sqlpage.ae8abf722876661d.js:16
    sqlpage_table https://ivz.infinitesidequests.com/sqlpage.ae8abf722876661d.js:42
    init_components https://ivz.infinitesidequests.com/sqlpage.ae8abf722876661d.js:206
    add_init_function https://ivz.infinitesidequests.com/sqlpage.ae8abf722876661d.js:202
    <anonymous> https://ivz.infinitesidequests.com/sqlpage.ae8abf722876661d.js:205
```
These errors do not manifest when running locally.

### Expected behavior

The tables render the same as they do when running locally.

### Version information

 - OS: Linux `6.6.13-gentoo`
 - Database: `PostgreSQL 16.3 on x86_64-pc-linux-gnu`
 - SQLPage Version: `sqlpage-v0.25.0.bin`

### Additional context
Maybe this is a timing issue that only happens on slower queries?

**Comment by guspower** [comment]
Similar error in Chrome:

```
sqlpage.ae8abf722876661d.js:16 Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')
    at i (sqlpage.ae8abf722876661d.js:16:11305)
    at sqlpage.ae8abf722876661d.js:16:13118
    at new e (sqlpage.ae8abf722876661d.js:16:13337)
    at t.exports (sqlpage.ae8abf722876661d.js:16:13370)
    at Object.start (sqlpage.ae8abf722876661d.js:16:2139)
    at new t.exports (sqlpage.ae8abf722876661d.js:16:4349)
    at sqlpage_table (sqlpage.ae8abf722876661d.js:42:9)
    at HTMLDocument.init_components (sqlpage.ae8abf722876661d.js:206:3)
```

**Comment by lovasoa** [comment]
Thanks for the report! 

This is going to be hard to debug without being able to reproduce it. Can you try to reproduce it reliably? Maybe by running a similarly configured nginx locally or simulating a slow network in your browser's network panel? 

In last resort, maybe you could give me access to a page online that reproduces the issue?

**Comment by lovasoa** [comment]
Do the local and remote versions contain the same data? could this be data dependent?

**Comment by guspower** [comment]
Yep good points +1 I will restore the production database locally and try to reproduce it, failing that I will try slow network in Firefox and see if that uncovers anything.

**Comment by lovasoa** [comment]
Given the stack trace, I think the error is thrown there: https://github.com/javve/list.js/blob/0c947162b5fc7af515ba2b9340b7e5e45a63fee5/src/templater.js#L66

But I can't say more without being able to reproduce.

**Comment by guspower** [comment]
OK I restored the prod database and can replicate it locally. Good call. Will now figure out what the data differences are.

**Comment by lovasoa** [comment]
Great ! Can you post the repro here ? 

Or, if it's hard to strip sensitive data, you can send it by email to `contact@ophir.dev`

**Comment by lovasoa** [comment]
I tried to reproduce it with very long tables and a slow network locally, to no avail. 

All I could do is break searching and sorting by naming a column `list`, which is a different problem, that we should still fix. 

I'm realizing that you mention a "loading spinner". There is no spinner when loading tables by default. Are you using the card component and loading the table from a different page ? Does the other page load correctly on its own ? Could you share your setup ?

**Comment by guspower** [comment]
OK I'm getting closer to being able to reproduce it. 

The flow is: outer page -> run_sql includes the sql containing the tables -> outer page finish.

Right now it appears that the error happens if/when the outer page renders a table after the chart, but the table is _empty_. Am gonna cook up a cleanroom example to see if I'm hallucinating.

**Comment by guspower** [comment]
Yep ok here are steps to reproduce:

`outer.sql`:
```

SELECT 'dynamic' AS component, sqlpage.run_sql('shell.sql') AS properties;

SELECT 
    'dynamic' AS component
    , sqlpage.run_sql('inner.sql') as properties;
    
select 
    'table' as component,
    TRUE    as sort,
    TRUE    as search;
--select  <- UNCOMMENT THIS BLOCK TO MAKE IT WORK
--    'Ophir'   as Forename,
--    'Lojkine' as Surname,
--    'lovasoa' as Pseudonym;
```

`inner.sql`:
```
select 
    'chart'             as component,
    'Quarterly Revenue' as title,
    'area'              as type,
    'indigo'            as color,
    5                   as marker,
    TRUE                as time;
select 
    '2022-01-01T00:00:00Z' as x,
    15                     as y;
```
Wild!

**Comment by lovasoa** [comment]
Excellent, thanks for the reproduction ! I'll look into it !

**Comment by lovasoa** [comment]
Ok, a shorter reproduction is just 

```sql
select 'table' as component, true as sort;
```

Empty sortable tables fail.

**Comment by lovasoa** [comment]
And the next problem is that a failure in any of the initialization functions prevents the next ones from running

https://github.com/lovasoa/SQLpage/blob/fc9fb618de9da41f618ee56ef1d7a7c475624424/sqlpage/sqlpage.js#L192-L196

**Comment by lovasoa** [comment]
Let's fix all that !
