### ISSUE TITLE
csv component: after the `#` will be truncated

### ISSUE THREAD

**Issue by BlueHtml** [lovasoa/SQLpage#525]
### Introduction

When there is a `#` in the CSV data, the data after the `#` will be truncated.

### To Reproduce

List of steps to reproduce the behavior. Include the sql file you are using and the eventual relevant parts of your database schema

```sql

select 
    'csv'              as component,
    'Download my data' as title,
    'people'           as filename,
    'file-download'    as icon,
    'green'            as color;

select 
top 100 *
from [Ban].[dbo].[Port];
```

### Screenshots

The data in the database is shown in the following figure:
![image](https://github.com/user-attachments/assets/2185eb1b-dcaf-4cbe-9bc8-bed849adfd99)

The generated html contains data after `#`, as shown in the following figure:
![image](https://github.com/user-attachments/assets/300159ee-5f83-45cc-aafa-2e153da0eed5)

Click the `download` button to download the file, and the data after `#` is gone. As shown in the following figure:
![image](https://github.com/user-attachments/assets/9ddc4a57-9a90-4a60-a707-fb65622e569e)

### Version information

 - OS: windows 10
 - Database [e.g. SQLite, Postgres]：mssql
 - SQLPage Version [found when hovering the default footer of pages]:SQLPage v0.26.0

**Comment by lovasoa** [comment]
Hi and welcome to SQLPage !

Thank you for the report; this is indeed a bug.

Until this is fixed, you can encode the problematic column manually in  sql:

```sql
select 
    'csv'              as component,
    'Download my data' as title,
    'people'           as filename,
    'file-download'    as icon,
    'green'            as color;

select 
  Id, ProjectId, REPLACE(Name, '#', '%23') as Name, Type
from [Ban].[dbo].[Port];
```
