### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by guspower** [lovasoa/SQLpage#526]
### Introduction

Despite using `ROUND` in `PostgreSQL` I am finding tabular and chart data containing unrounded values.

So while a result set may contain various values like `0.54`, `0.61` etc., occasionally there will be an unrounded value e.g. `0.7200000000000001`. This makes both tables and charts messy.

### To Reproduce

An example is one of the total revenue calculations that pulls data from a jsonb object and reports on it using a window function.

```sql
SELECT
    'Total Revenue £M' AS series
	, jsonb_path_query(data, '$.revenue.history[*].turn')::numeric AS x
	, jsonb_path_query(data, '$.revenue.history[*].total')::numeric AS y
FROM
	pricing.proposition
WHERE
    proposition_id = $proposition_id::numeric
ORDER BY x ASC
)
SELECT 
	series,
	x,
	ROUND((sum(y) OVER (PARTITION BY series ORDER BY x) / 1000000)::numeric, 2) AS y
FROM 
	monthly_revenue;
```

Running this using `pgAdmin4` gives me a dataset like:
![image](https://github.com/user-attachments/assets/c6fb98ee-eb62-47a2-99c3-e061814f5d85)

### Actual behavior

Instead I get data containing occasional unrounded values.

### Screenshots

![image](https://github.com/user-attachments/assets/e735aa30-5331-49cd-bbaa-b4e5ec764a89)

### Expected behavior

I had expected the use of `ROUND` to round the values and only data with that precision to be present in either the `SQLPage` tables or charts (or csv exports).

### Version information

 - OS: `Linux x86_64 6.6.13-gentoo`
 - Database: `PostgreSQL 16.3 on x86_64-pc-linux-gnu`
 - SQLPage Version: `v0.26.0`

**Comment by guspower** [comment]
A simpler, more reproducible set of examples:
```
SELECT 
    'chart' AS component
    , 'Rounding' AS title
    , TRUE AS debug
    ;
SELECT generate_series(1, 10) as x, ROUND(RANDOM()::numeric, 2) as y;

SELECT 
    'debug' AS component
    , 'Rounding' AS title
    , TRUE AS debug
    ;
SELECT generate_series(1, 10) as x, ROUND(RANDOM()::numeric, 2) as y;

SELECT 
    'table' as component
    ;
SELECT generate_series(1, 10) as x, ROUND(RANDOM()::numeric, 2) as y;
```

I don't know if this is a `sqlpage` bug or a problem between keyboard and chair. 
Any light you can throw on this would be great.

**Comment by lovasoa** [comment]
Thanks, I can reproduce it !

**Comment by lovasoa** [comment]
The issue can be reproduced with a file containing just

```sql
select 0.47::numeric;
```

When opened with sqlpage, this displays `0.47000000000000003`
