### ISSUE TITLE
csv component: Excel opens CSV files with garbled characters

### ISSUE THREAD

**Issue by BlueHtml** [lovasoa/SQLpage#528]
### Introduction

My Windows language environment is: Simplified Chinese `zh-CN`

My CSV file contains Chinese characters, but when I open it in Excel, garbled characters appear.
When the encoding of the CSV file is changed from `UTF-8` to `UTF-8 BOM`, the display in Excel is normal.

Can we add an option for users to choose between `UTF-8` or `UTF-8 BOM`?

### To Reproduce

```sql
select 
    'csv'              as component,
    'Download my data' as title,
    'people'           as filename,
    'file-download'    as icon,
    'green'            as color;

select 
top 100 *
from [Ban].[dbo].[Port];
```

### Screenshots

`UTF-8`: Opening with Excel will result in garbled characters, as shown below:
![image](https://github.com/user-attachments/assets/76abaabb-e880-4fef-a119-4b30c35bb67d)

`UTF-8 BOM`: When opened in Excel, it displays normally, as shown in the following figure:
![image](https://github.com/user-attachments/assets/95177bfa-e6fd-4daf-b0f9-8b59c7d11fec)

### Version information

 - OS: windowns 10 Simplified Chinese `zh-CN`
 - Database: `mssql`
 - SQLPage Version: `v0.26.0`

**Comment by lovasoa** [comment]
I'll see if we can add support for BOM to the CSV component.

In the meantime, you should be able to load the original CSV (without BOM) in excel by using `Data > Get Data > From File > From Text/CSV`

![image](https://github.com/user-attachments/assets/577b3709-4e86-45ca-94c3-7d953fd6e94e)
