### ISSUE TITLE
Add "sidebar-theme" in Shell Top-level parameters

### ISSUE THREAD

**Issue by Ajotah98** [lovasoa/SQLpage#540]
Hi,

Currently, the documentation of shell component only states about sidebar:
![image](https://github.com/user-attachments/assets/2571954a-ab8a-480f-bdac-7f0041dd73b5)

But when the sidebar component was created, we have included a "sidebar-theme" for letting people have "both" theme websites:

![image](https://github.com/user-attachments/assets/5b49180e-f27e-46c6-9843-e62ed59bbad1)

I guess the card with the info should be something like:

# sidebar-theme (Boolean, optional)
When used with the "sidebar" propery, it enables the dark theme only on the sidebar.

**Comment by lovasoa** [comment]
Oh, I missed that! Could we use the global theme by default, make this accept the same values as the theme parameter (instead of being a boolean), and use an underscore in the name? 

For the documentation, can you please open a pull request?

**Comment by lovasoa** [comment]
I'm open to a new pr to add a separate, documented, sidebar_theme, which falls back to the main theme when not specified :)

**Comment by Ajotah98** [comment]
Mmmm, I didn't put the sidebar-theme to fallback into the main theme! Instead, what I wanted is the possibility to have the sidebar in dark theme and the rest of the app in light theme.

Before the change, the behaviour was: 
if not sidebar-theme -> sidebar light, app light
if theme (global) -> sidebar dark, also app dark
if sidebar-theme (but not theme = dark) -> sidebar dark, app light

What do you think about?
