### ISSUE TITLE
Allowed variable to be used with function "sqlpage.read_file_as_text"

### ISSUE THREAD

**Issue by florian-bellencontre** [lovasoa/SQLpage#560]
_What are you building with SQLPage ?_

I'm creating a web interface to manage account creation and management via proftpd. And I want to add a toggle to activate the dark mode.

_What is your problem ? A description of the problem, not the solution you are proposing._

I'm looking to use the following toggle example:
https://github.com/lovasoa/SQLpage/tree/main/examples/light-dark-toggle

I'd like to use the dynamic component with a file and not by storing the information in a database.  

_What are you currently doing ? Since your solution is not implemented in SQLPage currently, what are you doing instead ?_

I currently have this code:
```
select 'dynamic' as component, sqlpage.read_file_as_text('shell.json') as properties;
```
shell.json
```
{
    "component": "shell",
    "title": "ProFTPD - admin",
    "layout": "vertical",
    "font": "Poppins",
    "icon": "folder-share",
    "__icon_list__": "https://tabler.io",
    "footer": "Infra",
    "link": "/",
    "sidebar": true,
    "theme": "dark",
    "menu_item": [
        {"link": "index.sql", "title": "Home"},
        {"link": "create.sql", "title": "Create SFTP"},
        {"link": "list.sql", "title": "SFTP list"},
        {"title":"☀","link":"/toggle.sql"}
    ]
}
```

I would like to be able to do this:
```
{
    "component": "shell",
...
    "theme": sqlpage.cookie('lightdarkstatus'),
...
}
```

I don't know if this is easily doable but it would be really cool.

Thanks in advance ;)

**Comment by lovasoa** [comment]
Hi! You can use https://sql.datapage.app/functions.sql?function=run_sql for that!

**Comment by lovasoa** [comment]
You can do it with

```sql
select 'dynamic' as component, sqlpage.run_sql('shell.sql') as properties;
```

and shell.sql :

```sql
select
    'shell' as component,
    sqlpage.cookie('lightdarkstatus') as theme;
``|
