### ISSUE TITLE
Doc: "foldable" example error in the doc page

### ISSUE THREAD

**Issue by mtt-artis** [lovasoa/SQLpage#572]
Hi 👋,

this is what I see on the foldable page
https://sql.datapage.app/component.sql?component=foldable

### Screenshots
![image](https://github.com/user-attachments/assets/8c35cb2d-7dc9-4afe-807b-316d4671dc7f)

### Additional
love the project !

**Comment by lovasoa** [comment]
Fixed ! Thanks for reporting the issue. I still haven't automated updating the official website to the latest development version of sqlpage.

I love that you love it ! What are you building with it ?

**Comment by mtt-artis** [comment]
an internal KPI dashboard at work.
it's the best tool for a great Time-to-Delivery
