### ISSUE TITLE
can't use big_numbers with a table

### ISSUE THREAD

**Issue by alexisrc1** [lovasoa/SQLpage#573]
### Introduction

When I use the big number component as in the example it works, but i created a table that has this formatting
![image](https://github.com/user-attachments/assets/e3c92976-b998-4061-8831-9c46d7644531)
It doesnt work

### Additional context
The issue is : change_percent needs to be an integer, it would be cool if it could be a numeric value !

**Comment by lovasoa** [comment]
The issue comes from handlebars only accepting integer comparisons. I'm opening an issue upstream.

**Comment by alexisrc1** [comment]
you're the man, thanks !

**Comment by lovasoa** [comment]
You can already have a string in `value`. But `change_percent` needs a number, in order to know whether to show the green or the red icon.

**Comment by alexisrc1** [comment]
other topic on this component : 
![image](https://github.com/user-attachments/assets/5bc77cc0-6427-42e6-95da-10d64204c944)
on mobile it displays weird (even worst on phone in portrait mode)

**Comment by lovasoa** [comment]
can we track this in a separate issue?
