### ISSUE TITLE
video doesnt play on mobile

### ISSUE THREAD

**Issue by alexisrc1** [lovasoa/SQLpage#575]
### Introduction

I added a video with the autoplay function, it works on a computer, but the video is not played on a smartphone.
I have an Iphone

**Comment by lovasoa** [comment]
this is probably related to https://webkit.org/blog/6784/new-video-policies-for-ios/

**Comment by lovasoa** [comment]
Apple forbids autoplaying videos with audio on iPhones. You can remove the sound from the video if you want it to autoplay on iPhones.
