### ISSUE TITLE
Favicon - A single favicon across all .sql pages

### ISSUE THREAD

**Issue by accforgithubtest** [lovasoa/SQLpage#592]
Want to request a feature which can make it easier to display a favicon across all the sqlpage pages.

One potential option would be to place a `favicon.ico` under the `/var/www` mapped volume, alongside the index.sql, and sqlpage picks up this as the favicon across the application.

Another potential option might be to specify a favicon as an environment var in the docker compose file, and place that icon in `/var/www`, which would be displayed across the application.

Going thru [the docs](https://sql.datapage.app/component.sql?component=shell), currently it looks like it is necessary to specify the favicon in shell component for each and every sql file.

Pls let me know if I have missed any available options to change the favicon across all pages without having to include this in each sql file. 

Cheers!

**Comment by lovasoa** [comment]
Hi !
  It is common to want to reuse the same properties (including the favicon) across pages in the shell component. The common solution is to use the [`dynamic`](https://sql.datapage.app/component.sql?component=dynamic) component, together with either [read_file_as_text](https://sql.datapage.app/functions.sql?function=read_file_as_text#function) (when the shell is exactly the same in all pages) or [run_sql](https://sql.datapage.app/functions.sql?function=run%5Fsql) (when we need to execute custom code to determine the appearance of the shell in each page).

**Comment by accforgithubtest** [comment]
run_sql seems to be the way to go. thank you for the detailed reply @lovasoa !

Cheers !
