### ISSUE TITLE
Treemap Chart - Ability to specify color for each data 

### ISSUE THREAD

**Issue by accforgithubtest** [lovasoa/SQLpage#593]
Would be nice to be able to specify the colors for each each of the data point in a treemap chart.

Currently this works and applies the color to all data in the chart -
```sql
select 
    'chart'   as component,
    'treemap' as type,
    'Quarterly Results By Region (in k$)' as title,
    'green' as color,
    TRUE      as labels;
```

while this does not work while attempting to specify color for each data in the chart - 
```sql
select 
    'North America' as series,
    'United States' as label,
    'orange' as color,
    35              as value;
select 
    'North America' as series,
    'Canada'        as label,
    'red' as color,
    15              as value;
select 
    'Europe'  as series,
    'Germany' as label,
    'blue' as color,
    55        as value;
```

**Comment by lovasoa** [comment]
Unfortunately, the properties are common to the entire chart component (and not specific per visualisation type). Colors are set as top-level properties, and they are not set per datapoint, but per series. 

You can still use one datapoint per series:

```sql
select 
    'chart'   as component,
    'treemap' as type,
    'Quarterly Results By Region (in k$)' as title,
    TRUE      as labels,
    'yellow'  as color,
    'purple'  as color,
    'cyan'    as color;
select 1 as series, 'United States' as label, 35 as value;
select 2 as series, 'France' as label, 30 as value;
select 3 as series, 'Germany' as label, 350 as value;
```

**Comment by accforgithubtest** [comment]
Thanks for the answer, using multiple color specs at the chart component works and I used a order by to ensure the ordering of the series in my results does not change.  This works now, and thank you !
