### ISSUE TITLE
Redirect component - Does not work with update queries ?

### ISSUE THREAD

**Issue by accforgithubtest** [lovasoa/SQLpage#618]
> A clear and concise description of what the bug is.

I am able to get the redirect component to work with insert statements, however update statements do not work, I see this error in the UI
```
error returned from database: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RETURNING 'redirect' AS component, concat('todo_person.sql?personId=', CAST(?...' at line 1

Backtrace
error returned from database: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RETURNING 'redirect' AS component, concat('todo_person.sql?personId=', CAST(?...' at line 1
```

### To Reproduce

A form with pid, record_id, record_ts, record_key, record_value as text / date / time fields.

`create_record.sql`
```
insert into test_table(record_id, record_ts, record_key, record_value) values($record_id, concat($yyyymmdd, ' ', $hhmmss), $record_key, $record_value)
returning 'redirect' as component, 
concat('home.sql?pid=', $pid) as link;
```
`update_record.sql`
```
update test_table set record_value=$record_value where record_id=$record_id
returning 'redirect' as component, 
concat('home.sql?pid=', $pid) as link;
```

### Actual behavior

```
error returned from database: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RETURNING 'redirect' AS component, concat('todo_person.sql?personId=', CAST(?...' at line 1

Backtrace
error returned from database: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RETURNING 'redirect' AS component, concat('todo_person.sql?personId=', CAST(?...' at line 1
```

### Expected behavior
I expected the update statement to complete and return to home.sql, I was expecting update to be working similar to insert.

### Version information

 - OS: Ubuntu 20.04
 - Database MariaDB
 - SQLPage Version v0.28.0

### Additional context
1. Deployed via docker.
2. Other components are working fine (cards, datagrid, etc.)
3. As mentioned above, issue is only with the update statement, insert flow is working fine.

**Comment by lovasoa** [comment]
Hello !
  Your problem is MariaDB, which does not support `UPDATE ... RETURNING`.

  In your case, since the returned value does not depend on the updated rows, you can just have a separate SELECT:

```sql
insert into test_table(record_id, record_ts, record_key, record_value) values($record_id, concat($yyyymmdd, ' ', $hhmmss), $record_key, $record_value);

select 'redirect' as component, 
concat('home.sql?pid=', $pid) as link;
```

In more complex cases, you could use [MariaDB's `REPLACE ... RETURNING`](https://mariadb.com/kb/en/replacereturning/) : 

```sql
replace into test_table 
values ($record_id, $record_value)
returning 'redirect' as component, 
concat('home.sql?pid=', $pid) as link;
```
