### ISSUE TITLE
Column Component - items not working in mysql

### ISSUE THREAD

**Issue by accforgithubtest** [lovasoa/SQLpage#633]
### Introduction

When attempting to use the new `columns` component, using Mysql database, the `item` are not being displayed.
Using the same example from documentation, only change is to use the `JSON_OBJECT` to generate json for item.

```sql
select 
    'columns' as component;

select 
    'Standard Plan' as title,
    '$49'           as value,
    'star'          as icon,
    'A standard plan for small teams.' as description,
	JSON_OBJECT("icon", "check", "color", "green", "description", "Collaboration Tools") as item,
	JSON_OBJECT("icon", "check", "color", "green", "description", "Custom data sources") as item,
	JSON_OBJECT("icon", "check", "color", "green", "description", "Priority support") as item,
    '#'             as link,
    'Select'        as button_text,
    'success'       as button_color,
    'green'         as value_color,
    '/month'        as small_text;
```

### Actual behavior

![image](https://github.com/user-attachments/assets/38a825dd-ce8f-4bfb-83c4-d272543fd916)

### Expected behavior
![image](https://github.com/user-attachments/assets/0aa911b2-3271-416d-915e-790fe0c1ae16)

**Comment by lovasoa** [comment]
Hello ! 

I'm sorry but I cannot reproduce your issue:

![image](https://github.com/user-attachments/assets/c4b988ca-4e69-4dc9-839b-6f1b818abe9d)


Could you give more information about how to reproduce the problem ?
Maybe replace `'columns' as component` with `'debug' as component` to be sure what your database returns.

**Comment by accforgithubtest** [comment]
Thanks for you reply @lovasoa !
I still see the issue in both firefox and chrome, using sqlpage v0.29.0.

Below is the debug output.
```
{"component":"debug"}
{"size":2,"title":"Standard Plan","value":"$49","icon":"star","description":"A standard plan for small teams.","item":["{\"icon\": \"check\", \"color\": \"green\", \"description\": \"Collaboration Tools\"}","{\"icon\": \"check\", \"color\": \"green\", \"description\": \"Custom data sources\"}","{\"icon\": \"check\", \"color\": \"green\", \"description\": \"Priority support\"}"],"link":"#","button_text":"Select","button_color":"success","value_color":"green","small_text":"/month"}

```

Is the item expected to be an array as seen above in debug ? Not sure where the array is coming from though, since the sql above only creates a json object.

**Comment by lovasoa** [comment]
Looks like you are using SQLite and not mysql. Look at the item elements: it's strings instead of objects. 

You can use the dynamic component to generate json objects in SQLite.

**Comment by accforgithubtest** [comment]
Thanks for the reply @lovasoa , I am using MariaDB, not mysql as I have mistakenly mentioned above, and its definitely not sqlite.

From the Database container logs -
```
Starting MariaDB 11.3.2-MariaDB-1:11.3.2+maria~ubu2204
```

From SQLPage logs - 
```
[2024-10-05T10:58:45.487Z INFO sqlpage::webserver::database::connect] Connecting to database: mysql://<user>:<pwd>@mariadb:3306/testdb
```

**Comment by lovasoa** [comment]
Contrarily to mysql, mariadb does not have a native json data type, and json functions in mariadb just return strings: https://mariadb.com/kb/en/json-data-type/

What you can do to make sqlpage parse these strings as json is use the dynamic component:


```sql
select 
    'columns' as component;
SELECT 'dynamic' as component,
  JSON_OBJECT(
    'title', 'Standard Plan',
    'value', '$49',
    'icon', 'star',
    'description', 'A standard plan for small teams.',
    'item', JSON_ARRAY(
        JSON_OBJECT('icon', 'check', 'color', 'green', 'description', 'Collaboration Tools'),
        JSON_OBJECT('icon', 'check', 'color', 'green', 'description', 'Custom data sources'),
        JSON_OBJECT('icon', 'check', 'color', 'green', 'description', 'Priority support')
    ),
    'link', '#',
    'button_text', 'Select',
    'button_color', 'success',
    'value_color', 'green',
    'small_text', '/month'
) AS properties;
```

**Comment by lovasoa** [comment]
I added a ne feature in the upcoming release to automatically detect json functions in sql queries, and parse the results as json even when the database returns it as text.

**Comment by accforgithubtest** [comment]
Thank you @lovasoa for the mariadb specific solution, and the new feature for json sounds great, look forward to the next release !
