### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nofue** [lovasoa/SQLpage#636]
### Introduction

On https://sql.datapage.app/component.sql?component=form
in row-level parameters -> max
the text reads: 

**max**
The **minimum** value to accept for an input of type number

Hope this helps ;)

**Comment by lovasoa** [comment]
thanks for reporting it ! That's fixed. Don't hesitate to report again if there is anything that looks wrong in the docs

**Comment by nofue** [comment]
Don't worry. It'd the least I can do for you. Spent most of today to get the first seven tables I'll need created as migrations for PostgreSQL. I think I'll spent some time on building the interface to these tables -- a bunch of CRUD files and plenty of tables from where users can step up or down the hierarchy. Should help me to understand the SQLPage mechanics better, and maybe I encounter some more bugs in the docs this way ;)
