### ISSUE TITLE
Documentation Errata

### ISSUE THREAD

**Issue by nofue** [lovasoa/SQLpage#639]
### Introduction

As I work through the docs, I put the errors I find in this list as a "one stop shop" for an editor …

### Here we go
As this is a rather long document, you might want to search to spot the spelling problem. Hence I give only one occurrence, there might be more 
https://sql.datapage.app/your-first-sql-website/
Optionnally -> optionally 

https://github.com/lovasoa/SQLpage/tree/main/examples/PostGIS%20-%20using%20sqlpage%20with%20geographic%20data
(sorry, I would have to "fork" … and as I don't know anything about this, I have not the time to make myself familiar with this stuff.)
**Introduction** 
greographic -> geographic

Same paragraph: "If you use sqllite instead…" Instead of what? I think postgreSQL should be mentioned first to use "instead" or right in the same paragraph as Option A and option B.

https://sql.datapage.app/your-first-sql-website/
Here, the verb "persisted" gets used more than once. As the state of the database is described, "persistent" should be used ("persisted" -> "persistent") as an attribute.

**Comment by lovasoa** [comment]
Fixed ! Thank you very much for reporting
