### ISSUE TITLE
Add an optional CSV export on chart component

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/SQLpage#65]
### Discussed in https://github.com/lovasoa/SQLpage/discussions/60

<div type='discussions-op-text'>

<sup>Originally posted by **pascalr0410** August 14, 2023</sup>
Hello,

Could it be possible to add an optional  "Download CSV" on each chart component, on the top right corner ?

It could reduce redudancy of sql and be more effiency usage of the screen space.

```sql
SELECT 'chart' as component, 'Expenses' as title, 'bar' as type, 1 as stacked, 1 as horizontal  , 
  1 as csvExport;
```

Regards,
Pascal.</div>

**Comment by lovasoa** [comment]
@pascalr0410 : This is now implemented, and will be in the next release of SQLPage. The syntax will be the following:

```sql
SELECT 'chart' as component, 1 as toolbar; -- displays a toolbar with download options
```

**Comment by pascalr0410** [comment]
@lovasoa  I tried it, it works great! :+1:
