### ISSUE TITLE
Broken click to sort table

### ISSUE THREAD

**Issue by nanawel** [lovasoa/SQLpage#67]
Since a recent release (I don't know exactly which one), a click on the header of a table component does not sort its content anymore, even when it's set as `1 AS 'sort'`. The arrow flips but the table remains unchanged.

Search still works though.

**Comment by lovasoa** [comment]
Fixed in https://github.com/lovasoa/SQLpage/commit/5fc00bda0cd84337475c526116e63f0cce2304ca 

Will be in v0.10.1
