### ISSUE TITLE
How to set Form type date to current date or start of week

### ISSUE THREAD

**Issue by jahelo** [lovasoa/SQLpage#70]
Is there a built-in way to set a control of type date to e.g. the current date?

I did not find it in the documentation. I found the possibility to set it to a specific date, but i would like to be able to set it to the current date or start of the week etc.

**Comment by lovasoa** [comment]
You can use your databases native functions for that. What database are you using?

**Comment by lovasoa** [comment]
Here is an example with SQLite :

```sql
select 'form' as component;
select 'date' as type, date('now') as value;
```

![image](https://github.com/lovasoa/SQLpage/assets/552629/d3308a6d-9464-4c46-90be-cc6c6330c68e)
