### ISSUE TITLE
SQL Server named instance database_url

### ISSUE THREAD

**Issue by spiralcb** [lovasoa/SQLpage#92]
Hello, 

Very fun project, I'm trying it using SQL Server. 

Could you give me an example of database_url for a SQL Server named instance with user and password please ? 

Thanks in advance

**Comment by lovasoa** [comment]
Hello and welcome to SQLPage !

Currently, SQLPage requires you to manually enter the port your database is lstening on when connecting to a named sql server instance. See:  https://github.com/lovasoa/SQLpage/issues/86

An example connection string would be `mssql://username:password@localhost:2179/YourDatabaseName?instance=YourInstanceName`, where you would replace 2179 with the port your instance is listening on, which you can [find in the SQL Server configuration manager](https://www.mssqltips.com/sqlservertip/2495/identify-sql-server-tcp-ip-port-being-used/)

**Comment by spiralcb** [comment]
Thanks a lot, it wroks

**Comment by yx3016** [comment]
Excuse me, how can I solve this TLS encryption link error prompt?

<img width="1526" height="536" alt="Image" src="https://github.com/user-attachments/assets/27f42011-872c-420c-b7f2-eb0e2165b9e0" />

**Comment by lovasoa** [comment]
`encrypt=false` is unintuitive in SQL server: https://docs.rs/sqlx-oldapi/latest/sqlx_oldapi/mssql/struct.MssqlConnectOptions.html#method.from_str

Maybe you meant `encrypt=not_supported` ?

**Comment by yx3016** [comment]
非常感谢，终于运行起来了。

---

translation: Thank you so much, it finally runs!
