### ISSUE TITLE
Docker hub image tagging strategy

### ISSUE THREAD

**Issue by edgrip** [lovasoa/SQLpage#97]
Hello @lovasoa ,
I would suggest adjustments on docker image publication strategy.
The current setup can lead to nasty side effects for people who get SQLpage through docker hub.

- latest tag should point to the latest release instead of the latest build.
- every release should have a corresponding tag.

As of time of writing this issue, latest comes with unreleased v0.13.0, and v0.12.0 does not have its own image.
Kind regards.

**Comment by lovasoa** [comment]
It should be fixed now. Thanks for reporting the issue ! Let me know if you encounter problems with the docker images.

**Comment by edgrip** [comment]
Hello @lovasoa , thanks a lot, I did few quick checks (pulled again latest and pulled v0.12.0), seems ok (shows the expected version for each)
