### ISSUE TITLE
Did 0.12.0 release get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [lovasoa/SQLpage#99]
👋 while upgrading rust to 1.73.0, we found that the 0.12.0 release tarball file shasum got changed. Raise this issue to confirm it is intended. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/150415

**Comment by lovasoa** [comment]
Yes, I'm sorry, I had to re-tag it because of https://github.com/lovasoa/SQLpage/issues/97

This should not happen again in the future

**Comment by chenrui333** [comment]
@lovasoa np at all, thanks for confirming it!
